/* Les 38 fiches techniques de Natty (dossier « fiche rectte natty », septembre 2026),
   transcrites depuis les .docx. Toutes sont écrites POUR 6 PORTIONS (la dernière
   fiche le dit : « permettant de réaliser 6 portions » — et les 6 filets, 6
   tortillas, 6 cuisses le confirment).

   FORMAT — volontairement compact, pour qu'on puisse relire 38 fiches d'un coup :
     ing  : "nom | grammes pour 6 portions | quantité telle qu'écrite sur la fiche"
            ⚠️ les féculents (riz, quinoa, lentilles, boulgour, millet) sont en
            poids CUIT dans `g`, comme l'attend la table de core.js — le `qte`
            affiché dit le cru (voir scripts/injecter-recettes.mjs).
            Une conserve « 400 g » égouttée pèse ~250 g ; une tasse fait 240 ml.
     etape: "geste | aliment | durée min | drapeaux | titre | description | °C | dépend de"
            Le 7ᵉ champ (facultatif) est la TEMPÉRATURE de l'étape (four, cœur,
            liquide) : il va dans recettes_etapes.temperature_c, que Production
            affiche et qui ajoute la sonde au matériel.
            Le 8ᵉ (facultatif) : les NUMÉROS des étapes de la même fiche que
            celle-ci attend ("3,5"), pour recettes_etapes.depend_de — à poser
            là où l'inférence par l'aliment se trompe (un mot de plat qui
            retombe sur un ingrédient, une « même poêle » que rien ne nomme).
            geste ∈ les 16 gestes d'assets/recette.js (couper, saisir, bouillir,
            mijoter, enfourner, melanger, fouetter, mixer, assaisonner, huiler,
            rincer, peser, refrigerer, reposer, attendre, dresser) — c'est ce
            que l'onglet Production trie ; aliment = ce sur quoi porte le geste.
            drapeaux : P = passif (four, mijotage, marinade : le cuisinier est
            libre), A = assemblage (par portion, pas en masse). Une durée non
            écrite sur la fiche est ESTIMÉE — la fiche ne donne que les temps de
            cuisson, jamais ceux de découpe.
   code : PS = prise de masse (le titre du Bourguignon PS le dit), PP = perte de
          poids, PM = ?, VG = végétarien, SG = sans gluten. 🔄 PM à confirmer par Pablo.
   « Steak de thon salsa mango PS (2).docx » est un doublon du Risotto de boulgour
   SG (même contenu) : ignoré. */
export const PORTIONS = 6;

export const FICHES = [
{ nom: 'Boulettes de dinde, salade de chou', code: 'SG', fichier: 'Boulette de dinde SG',
  desc: 'Boulettes de dinde dorées à la poêle, salade de chou râpé au yaourt grec et à l’ail.',
  ing: ['dinde hachée|1200|1,2 kg', 'chapelure sans gluten|60|1/2 tasse', 'lait|60|1/4 tasse', 'oeuf|55|1',
    'oignon|150|1', 'ail|10|2 gousses', 'persil|5|1 c. à s.', 'huile olive|42|3 c. à s.', 'chou|600|600 g râpé',
    'yaourt grec|150|150 g', 'ail|15|3 c. de pulpe', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, ail, persil|8||Hacher oignon, ail et persil|Oignon ciselé à 3 mm (racine gardée pendant la coupe). Ail : écraser, peler, retirer le germe, hacher fin. Persil lavé, ESSORÉ, haché en trois passes — pas plus, il noircit. Réserver les trois séparément.',
    'melanger|dinde hachée|10||Façonner les boulettes|Chapelure (60 g) trempée dans le lait (60 ml) 5 min. Dinde FROIDE, œuf, oignon, ail, persil, 12 g de sel (1 % du poids), poivre. Mélanger à la main 1 min, juste homogène — pas plus, elle devient élastique. Cuire une mini-boulette à la poêle, goûter, rectifier le sel. Mains mouillées, former 30 boulettes de 45 g (une cuillère à glace rase), rouler sans serrer.',
    'refrigerer|boulettes de dinde|20|P|Raffermir au froid|Boulettes sur plaque filmée, 20 min au réfrigérateur : elles tiendront à la poêle.',
    'saisir|boulettes de dinde|15||Dorer les boulettes|Poêle chaude, 3 c. à s. d’huile d’olive, feu moyen-vif. Boulettes espacées, en 2 lots. Ne pas toucher 3 min ; rouler d’un quart de tour quand la face se décolle ; 8–10 min pour dorer toutes les faces. Puis feu moyen, couvercle, 4–5 min. Sonde : 74 °C à cœur, jus clair.|74',
    'couper|chou|6||Émincer le chou|Chou : feuilles abîmées retirées, coupé en quartiers, trognon retiré en biais. Émincé à 2 mm à la mandoline (garde-main) ou au couteau bien affûté.',
    'melanger|chou râpé|10||Salade de chou|Chou émincé à 2 mm, 6 g de sel, 15 min dans une passoire : il rend son eau et s’assouplit. Presser. Ail écrasé en pâte avec une pincée de sel (15 g), yaourt grec (150 g), poivre. Mélanger, goûter : acide net, salé juste.',
    'refrigerer|boulettes|30|P|Refroidir|Boulettes étalées sur plaque en cellule ou au frais à découvert jusqu’à 10 °C à cœur (moins de 2 h). Une boîte fermée chaude fait de la buée et détrempe la salade.',
    'dresser|boulettes + salade de chou|2|A|Dresser|Tare avec la boîte. 5 boulettes (≈ 200 g cuit) d’un côté, 120 g de salade de chou de l’autre — jamais mélangés, la salade rendrait son eau. Opercule sans buée, étiquette.'] },

{ nom: 'Bœuf bourguignon (prise de masse)', code: 'PS', fichier: 'Bourguignon PS',
  desc: 'Bœuf mijoté au vin rouge, carottes, champignons, servi avec des pommes de terre.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|720|6', 'oignon|450|3', 'vin rouge|0|1,5 L (alcool évaporé : non compté)',
    'bouillon de boeuf|750|750 ml', 'champignons|300|300 g', 'farine|30|3 c. à s.', 'huile olive|42|3 c. à s.',
    'thym|0|3 branches', 'laurier|0|3 feuilles', 'pomme de terre|1500|1,5 kg', 'sel|0|q.s.'],
  etapes: [
    'couper|boeuf, carottes, oignons, champignons|20||Tailler|Bœuf (gîte ou paleron) : retirer nerfs et membranes, garder le gras intramusculaire, cubes de 4–5 cm EN TRAVERS des fibres — il rétrécit d’un quart. Carottes en rondelles en biseau de 1 cm. Oignons émincés à 3 mm. Champignons : pied talé, nettoyés à sec, en quartiers de 2–3 cm. Bacs séparés.',
    'assaisonner|boeuf|3||Sécher et saler le bœuf|Cubes séchés au papier absorbant (une surface mouillée bout au lieu de dorer), 12 g de sel, poivre. 10 min avant de dorer.',
    'saisir|boeuf|12||Dorer le bœuf|Cocotte à feu vif, 3 c. à s. d’huile à peine fumante. Cubes en 3–4 lots, 1 cm entre chaque, jamais plus de la moitié du fond. Ne pas toucher 2 min, retourner, 1,5 min par face, 3 faces. Croûte BRUNE, pas grise. Réserver dans un plat. Essuyer le fond s’il noircit entre deux lots.',
    'saisir|oignons, carottes|8||Revenir les légumes|Même cocotte, feu moyen-vif, dans le gras et les sucs. Oignons et carottes, pincée de sel, 6–8 min : oignons translucides, carottes dorées sur les bords. Gratter les sucs avec 2 c. à s. d’eau s’ils attachent.',
    'melanger|boeuf, farine|3||Singer|Remettre la viande et son jus. Saupoudrer 30 g de farine en pluie sur tout, remuer 2 min à feu moyen : la farine disparaît et blondit. C’est ce qui liera la sauce sans grumeau.',
    'assaisonner|vin, bouillon, thym, laurier|5||Mouiller|Feu vif, verser le vin rouge (1,5 l), gratter le fond : les sucs se dissolvent. 2–3 min : l’odeur d’alcool disparaît. Bouillon CHAUD (750 ml) à hauteur — le liquide affleure la viande. Thym et laurier liés en bouquet. Sel léger, poivre.||4,5',
    'mijoter|bourguignon|150|P|Mijoter 2 h 30|Ébullition une fois, puis frémissement : une bulle par seconde, feu minimum (ou four à 150 °C, plus régulier), couvert. Toutes les 30 min : remuer en grattant le fond, vérifier le liquide. À 2 h : champignons. À 2 h 30 : la fourchette entre dans un cube sans forcer et il se sépare sous une pression légère ; sinon 30 min de plus. Dégraisser à la cuillère, retirer le bouquet, rectifier le sel.|92',
    'bouillir|pommes de terre|25||Cuire les pommes de terre|Pelées, cubes de 3 cm, gardées sous l’eau froide. Départ eau FROIDE salée (10 g/l), 3 cm au-dessus. Ébullition puis bouillon modéré, 20–25 min : la pointe du couteau entre sans résistance. Égoutter, 1 min dans la casserole sur le feu éteint pour sécher.',
    'refrigerer|bourguignon|40|P|Refroidir|Bourguignon et pommes de terre étalés en bacs de 5 cm, cellule ou bain glacé, jusqu’à 10 °C à cœur en moins de 2 h.',
    'dresser|bourguignon + pommes de terre|2|A|Dresser|Tare. 250 g de pommes de terre au fond, 250 g de bœuf avec ses carottes et champignons, 2 louches de sauce. Pas de feuille de laurier dans la boîte (les compter). Opercule sans buée, étiquette.'] },

{ nom: 'Bourguignon by Natty (sans gluten)', code: 'SG', fichier: 'Bourguignon by natty SG',
  desc: 'Le bourguignon, lié à la farine de riz : sans gluten.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|720|6', 'oignon|450|3', 'vin rouge|0|1,5 L (alcool évaporé : non compté)',
    'bouillon de boeuf|750|750 ml', 'champignons|300|300 g', 'farine de riz|30|3 c. à s.', 'huile olive|42|3 c. à s.',
    'thym|0|3 branches', 'laurier|0|3 feuilles', 'pomme de terre|1500|1,5 kg', 'sel|0|q.s.'],
  etapes: [
    'couper|boeuf, carottes, oignons, champignons|20||Tailler|Bœuf : nerfs et membranes retirés, gras intramusculaire gardé, cubes de 4–5 cm en travers des fibres. Carottes en biseau de 1 cm. Oignons émincés à 3 mm. Champignons nettoyés à sec, en quartiers. Bacs séparés.',
    'assaisonner|boeuf|3||Sécher et saler le bœuf|Cubes séchés au papier, 12 g de sel, poivre, 10 min avant de dorer.',
    'saisir|boeuf|12||Dorer le bœuf|Cocotte à feu vif, 3 c. à s. d’huile à peine fumante. 3–4 lots, cubes espacés, 2 min sans toucher puis 1,5 min par face. Croûte brune. Réserver.',
    'saisir|oignons, carottes|8||Revenir les légumes|Même cocotte, feu moyen-vif, pincée de sel, 6–8 min : oignons translucides, carottes dorées sur les bords.',
    'melanger|boeuf, farine de riz|3||Lier à la farine de riz|Remettre la viande. 30 g de farine de riz en pluie, remuer 2 min à feu moyen. La farine de riz lie moins que la farine de blé : la sauce sera un peu plus fluide, c’est normal.',
    'assaisonner|vin, bouillon, thym, laurier|5||Mouiller|Vin rouge (1,5 l) à feu vif en grattant le fond, 2–3 min jusqu’à ce que l’alcool ne pique plus le nez. Bouillon CHAUD (750 ml) à hauteur, bouquet de thym et laurier, sel léger, poivre.||4,5',
    'mijoter|bourguignon|150|P|Mijoter 2 h 30|Frémissement, feu minimum ou four 150 °C, couvert. Remuer toutes les 30 min. Champignons à 2 h. Prêt quand la fourchette entre sans forcer dans un cube. Dégraisser, retirer le bouquet, rectifier.|92',
    'bouillir|pommes de terre|25||Cuire les pommes de terre|Cubes de 3 cm, départ eau froide salée (10 g/l), 20–25 min, couteau qui entre sans résistance. Égoutter, sécher 1 min.',
    'refrigerer|bourguignon|40|P|Refroidir|Bacs de 5 cm, cellule ou bain glacé, 10 °C à cœur en moins de 2 h.',
    'dresser|bourguignon + pommes de terre|2|A|Dresser|Tare. 250 g de pommes de terre, 250 g de bœuf et garniture, 2 louches de sauce. Laurier compté et retiré. Opercule sans buée, étiquette.'] },

{ nom: 'Burger de lentilles', code: 'PS', fichier: 'Burger de lentilles PS',
  desc: 'Galettes de lentilles et chou-fleur, pain complet, avocat, tomate, salade.',
  ing: ['lentilles|400|2 tasses cuites', 'chou-fleur|200|1 tasse cuit', 'flocons avoine|45|1/2 tasse', 'oignon|150|1',
    'ail|10|2 gousses', 'cumin|6|1 c. à s.', 'sauce soja|15|1 c. à s.', 'huile olive|28|2 c. à s.', 'pain complet|360|6 pains',
    'avocat|170|1', 'tomate|240|2', 'salade|90|quelques feuilles', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, ail|5||Hacher oignon et ail|Oignon ciselé à 3 mm. Ail dégermé, haché fin.',
    'saisir|oignon, ail|6||Faire suer|Poêle, 1 c. à s. d’huile, feu moyen. Oignon avec une pincée de sel 5 min jusqu’à translucide ; ail 30 s en remuant, sans le laisser brunir. Réserver, laisser tiédir.',
    'mixer|lentilles, chou-fleur, flocons|8||Écraser la farce|Lentilles cuites ÉGOUTTÉES à fond, chou-fleur cuit et pressé, flocons d’avoine (45 g), cumin (6 g), sauce soja (15 g), oignon et ail refroidis, sel, poivre. Fourchette ou 5–8 impulsions au mixeur : texture de gros sable qui se tient quand on presse — pas une purée lisse.',
    'refrigerer|farce de lentilles|15|P|Reposer la farce|15 min au frais : les flocons gonflent et lient. Sans ce repos, les galettes s’effritent.',
    'melanger|farce de lentilles|8||Former les galettes|Mains mouillées, 6 palets de 1,5 cm d’épaisseur et 9 cm de diamètre, pressés fermement entre les paumes. Sur plaque filmée.',
    'saisir|galettes de lentilles|14||Cuire les galettes|Poêle antiadhésive, 1 c. à s. d’huile, feu moyen. 5–6 min sans toucher : la croûte se forme. UN seul retournement à la spatule large, 5–6 min. Dorées et fermes.',
    'couper|avocat, tomate|5|A|Tailler la garniture|Avocat en tranches de 1 cm, citronnées aussitôt. Tomate en rondelles de 5 mm, épépinée si elle coule. Salade lavée, essorée.',
    'dresser|burger|3|A|Monter le burger|Pain complet ouvert, salade sur la base (elle protège le pain de l’humidité), galette refroidie à 10 °C, avocat, tomate, chapeau. Un burger par boîte, étiquette.'] },

{ nom: 'Burritos végétariens au quinoa', code: 'SG', fichier: 'Buritos vegetarien au quinoa SG',
  desc: 'Tortillas de maïs garnies de quinoa, haricots noirs, avocat, tomate, maïs et coriandre.',
  ing: ['quinoa|510|1 tasse (cru) → cuit', 'haricots noirs|250|1 boîte égouttée', 'avocat|170|1', 'tomate|120|1',
    'oignon rouge|75|1/2', 'poivron rouge|150|1', 'mais|80|1/2 tasse', 'coriandre|10|1/4 tasse', 'tortilla mais|360|6',
    'jus de citron|40|1 citron', 'sel|0|q.s.'],
  etapes: [
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, remuer à la main jusqu’à ce que l’eau ne mousse plus (la saponine est amère).',
    'bouillir|quinoa|15|P|Cuire le quinoa|1 volume de quinoa, 2 volumes d’eau, 4 g de sel. Ébullition, couvercle, feu minimum 12–15 min. Hors du feu, couvert, 5 min. Chaque grain montre son petit anneau blanc. Égrener à la fourchette, étaler sur plaque pour refroidir.',
    'couper|avocat, tomate, oignon rouge, poivron, coriandre|12||Tailler|Avocat en dés de 1,5 cm, citronnés aussitôt. Tomate épépinée en dés de 1 cm. Poivron : côtes et graines retirées, peau contre la planche, dés de 1 cm. Oignon rouge ciselé fin, 10 min dans l’eau froide, égoutté. Coriandre (tiges comprises) hachée au dernier moment.',
    'melanger|haricots noirs, légumes|4||Mélanger la garniture|Haricots noirs rincés 30 s et égouttés, maïs égoutté, avocat, tomate, oignon, poivron, coriandre. Soulever à la maryse, pas tourner : l’avocat s’écrase.',
    'assaisonner|garniture au quinoa|3||Assaisonner|Quinoa FROID incorporé, jus de citron (40 g), 6 g de sel, poivre. Goûter : acide net. Rectifier.||2,4',
    'saisir|tortillas|4|A|Chauffer les tortillas|Poêle sèche à feu vif, 20–30 s par face : cloques et taches brunes. Empiler sous un torchon.',
    'dresser|burrito|3|A|Garnir et rouler|Tortilla à plat, 200 g de garniture en bande au centre, bords rabattus puis rouler serré. Couper en deux en biais. Une par boîte, étiquette.'] },

{ nom: 'Bœuf braisé aux légumes', code: 'PM', fichier: 'Bœuf braisé PM',
  desc: 'Cubes de bœuf braisés au bouillon avec carottes, céleri et oignon.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|480|4', 'celeri|100|2 branches', 'oignon|150|1',
    'bouillon de boeuf|750|750 ml', 'huile olive|42|3 c. à s.', 'laurier|0|2 feuilles', 'thym|0|3 branches', 'sel|0|q.s.'],
  etapes: [
    'couper|boeuf, carottes, céleri, oignon|15||Tailler|Bœuf : nerfs retirés, gras gardé, cubes de 4–5 cm en travers des fibres. Carottes en rondelles de 1 cm en biseau. Céleri effilé à l’économe, dés de 1 cm. Oignon ciselé à 5 mm.',
    'assaisonner|boeuf|3||Sécher et saler|Cubes séchés au papier absorbant, 12 g de sel, poivre.',
    'saisir|boeuf|12||Saisir le bœuf|Cocotte à feu vif, 3 c. à s. d’huile à peine fumante, 3–4 lots, cubes espacés. 2 min sans toucher, puis 1,5 min par face. Croûte brune sur 3 faces. Réserver.',
    'saisir|oignon, carottes, céleri|6||Revenir les légumes|Même cocotte, feu moyen-vif, pincée de sel, 5–6 min : oignon translucide, carottes dorées sur les bords. Gratter les sucs.',
    'assaisonner|bouillon, laurier, thym|3||Mouiller|Remettre la viande. Bouillon de bœuf CHAUD (750 ml) à hauteur, thym et laurier en bouquet, sel léger, poivre.||3,4',
    'mijoter|boeuf braisé|150|P|Braiser 2 h 30|Frémissement (une bulle par seconde), couvert, feu minimum ou four 150 °C. Remuer toutes les 30 min. À 2 h 30 la fourchette entre sans forcer ; sinon 30 min de plus. Dégraisser, retirer le bouquet, rectifier le sel.|92|5',
    'refrigerer|boeuf braisé|40|P|Refroidir|Bacs de 5 cm, cellule ou bain glacé, 10 °C à cœur en moins de 2 h.',
    'dresser|boeuf braisé|2|A|Dresser|Tare. 250 g de bœuf avec ses légumes, 2 louches de sauce. Opercule sans buée, étiquette.'] },

{ nom: 'Cabillaud et pois chiches', code: 'PM', fichier: 'Cabillaud et pois chiches PM',
  desc: 'Filet de cabillaud poêlé, sauté de pois chiches et épinards à l’ail, jus de citron.',
  ing: ['cabillaud|900|6 filets', 'pois chiches|500|2 boîtes égouttées', 'epinards|300|300 g frais', 'huile olive|42|3 c. à s.',
    'jus de citron|45|3 c. à s.', 'ail|10|2 gousses', 'sel|0|q.s.'],
  etapes: [
    'couper|ail|2||Émincer l’ail|Gousses écrasées du plat de la lame, pelées, dégermées, émincées à 1 mm.',
    'rincer|pois chiches, épinards|4||Rincer et sécher|Pois chiches rincés 30 s, égouttés, ÉTALÉS sur un torchon 10 min : secs, ils croustilleront. Épinards lavés en deux bains, essorés à fond.',
    'assaisonner|cabillaud|3||Sécher et saler le cabillaud|Filets séchés au papier des deux côtés, 9 g de sel, poivre, 5 min. Resécher.',
    'saisir|cabillaud|10||Cuire le cabillaud|Poêle chaude, 2 c. à s. d’huile à peine fumante, feu moyen-vif. Filets posés côté peau (ou le côté le plus plat) en s’éloignant de soi, 10 s de pression à la spatule. 4 min sans toucher : la chair devient opaque en montant sur le côté. Un seul retournement, 1–2 min. Sonde : 63 °C. Réserver.|63',
    'saisir|pois chiches, épinards|6||Sauter pois chiches et épinards|Même poêle, reste d’huile, feu vif. Pois chiches secs 4 min en secouant : dorés. Ail 30 s. Épinards par poignées, retournés à la pince, 1–2 min : ils tombent à 1/10. Sel, poivre à la fin. Égoutter dans une passoire en pressant.||1,2,4',
    'refrigerer|cabillaud|30|P|Refroidir|Cabillaud et pois chiches étalés sur plaque, cellule ou frais à découvert, 10 °C à cœur en moins de 2 h.',
    'dresser|cabillaud + pois chiches|2|A|Dresser|Tare. 150 g de pois chiches-épinards au fond, un filet de cabillaud (150 g) dessus, 1 c. à c. de jus de citron. Opercule sans buée, étiquette.'] },

{ nom: 'Chili con carne', code: 'SG', fichier: 'Chili con carne SG',
  desc: 'Bœuf haché mijoté aux haricots rouges et noirs, tomates, chili et cumin, avec du riz.',
  ing: ['boeuf hache|1500|1,5 kg', 'haricots rouges|250|1 boîte égouttée', 'haricots noirs|250|1 boîte égouttée',
    'tomates concassees|400|1 boîte', 'oignon|150|1', 'ail|20|4 gousses', 'chili en poudre|12|2 c. à s.', 'cumin|6|1 c. à s.',
    'huile olive|42|3 c. à s.', 'riz|1200|~460 g cru → cuit', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, ail|5||Hacher oignon et ail|Oignon ciselé à 3 mm. Ail dégermé, émincé fin.',
    'saisir|boeuf haché|10||Dorer le bœuf haché|Casserole large ou sauteuse à feu vif, 2 c. à s. d’huile. Bœuf en 3 lots de 500 g, cassé en morceaux de 3 cm, 2–3 min sans remuer : l’eau sort et s’évapore (le chuintement devient un grésillement), puis la coloration commence. Casser plus fin, 5–6 min jusqu’à brun partout. Réserver.',
    'saisir|oignon, ail|5||Faire suer|Même casserole, feu moyen, 1 c. à s. d’huile. Oignon et pincée de sel 4–5 min jusqu’à translucide, ail 30 s.',
    'melanger|épices|1||Fleurir les épices|Chili en poudre (12 g) et cumin (6 g) dans le gras chaud, 30–60 s en remuant sans arrêt : le parfum monte, la couleur fonce. Ne pas attendre la fumée.',
    'melanger|tomates, haricots|3||Incorporer|Remettre le bœuf. Tomates concassées (400 g) et 400 ml d’eau ou de bouillon chaud. Haricots rouges et noirs rincés 30 s et égouttés : les garder pour les 15 dernières minutes.',
    'mijoter|chili|45|P|Mijoter 45 min|Frémissement, couvercle entrouvert, feu doux. Remuer toutes les 10 min en grattant le fond. À 30 min : haricots. Prêt quand il est épais — une cuillère plantée tient debout — sans eau libre en surface. 12 g de sel, poivre, goûter.|90',
    'rincer|riz|3||Rincer le riz|Riz dans un bol, eau froide, frotter à la main, vider l’eau blanche. 3–4 fois, jusqu’à l’eau claire. Égoutter.',
    'bouillir|riz|22||Cuire le riz|1 volume de riz, 1,5 volume d’eau froide, 4 g de sel. Ébullition sans couvercle, puis couvercle, feu minimum 10–12 min. Feu coupé, couvert, 10 min. Ne jamais soulever le couvercle. Égrener, étaler sur plaque.',
    'refrigerer|chili|40|P|Refroidir|Chili en bacs de 5 cm, riz étalé sur plaque, cellule ou bain glacé, 10 °C à cœur en moins de 2 h.',
    'dresser|chili + riz|2|A|Dresser|Tare. 200 g de riz au fond, 300 g de chili dessus, séparés si la boîte a deux compartiments (le riz boirait la sauce). Opercule sans buée, étiquette.'] },

{ nom: 'Chili sin carne, haricots noirs et quinoa', code: 'PS', fichier: 'Chili sin carne PS',
  desc: 'Chili végétarien : haricots noirs, tomates, poivron, quinoa, avocat en condiment.',
  ing: ['quinoa|510|1 tasse (cru) → cuit', 'haricots noirs|250|1 boîte égouttée', 'tomates concassees|400|1 boîte', 'poivron rouge|150|1',
    'oignon|150|1', 'ail|10|2 gousses', 'chili en poudre|12|2 c. à s.', 'cumin|6|1 c. à s.', 'huile olive|14|1 c. à s.', 'avocat|170|1', 'sel|0|q.s.'],
  etapes: [
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, jusqu’à ce que l’eau ne mousse plus.',
    'bouillir|quinoa|15|P|Cuire le quinoa|1 volume de quinoa, 2 volumes d’eau, 4 g de sel. Ébullition, couvercle, feu minimum 12–15 min, puis 5 min hors du feu couvert. Anneau blanc visible sur chaque grain. Égrener.',
    'couper|oignon, ail, poivron|8||Tailler|Oignon ciselé à 3 mm. Ail dégermé, émincé. Poivron sans côtes ni graines, peau contre la planche, dés de 1 cm.',
    'saisir|oignon, ail, poivron|6||Revenir|Casserole, 1 c. à s. d’huile, feu moyen-vif. Oignon et poivron avec une pincée de sel 5 min : oignon translucide, poivron marqué. Ail 30 s.',
    'melanger|épices|1||Fleurir les épices|Chili en poudre (12 g) et cumin (6 g) dans le gras chaud, 30–60 s en remuant : le parfum monte.',
    'melanger|tomates, haricots noirs|2||Ajouter tomates et haricots|Tomates concassées (400 g), 200 ml d’eau chaude. Haricots noirs rincés et égouttés.',
    'mijoter|chili sin carne|18|P|Mijoter 15–20 min|Frémissement, couvercle entrouvert. Remuer toutes les 5 min. Prêt quand épais et sans eau libre.|90',
    'assaisonner|chili + quinoa|3||Incorporer le quinoa|Feu coupé, quinoa cuit incorporé à la maryse. 8 g de sel, poivre, goûter — le quinoa absorbe du sel.',
    'refrigerer|chili sin carne|40|P|Refroidir|Bacs de 5 cm, cellule ou bain glacé, 10 °C à cœur en moins de 2 h.',
    'couper|avocat|3|A|Avocat en dés|Fendu, noyau retiré à la cuillère, dés de 1,5 cm, jus de citron aussitôt.',
    'dresser|chili sin carne|2|A|Dresser|Tare. 350 g de chili-quinoa, 55 g de dés d’avocat dessus. Opercule sans buée, étiquette.||9,10'] },

{ nom: 'Courgettes farcies au quinoa', code: 'SG', fichier: 'Courgettes farcies SG',
  desc: 'Barques de courgette farcies au quinoa, poivron et tomate, cuites sur un lit de sauce tomate.',
  ing: ['courgette|1200|6', 'quinoa|540|1,5 tasse (cuit)', 'poivron rouge|150|1', 'oignon|150|1', 'tomate|240|2',
    'sauce tomate|400|1 boîte', 'huile olive|28|2 c. à s.', 'basilic|3|q.s.', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer le four|190 °C, chaleur tournante. 15 min avant d’enfourner.|190',
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, jusqu’à zéro mousse.',
    'bouillir|quinoa|15|P|Cuire le quinoa|1 volume, 2 volumes d’eau, 4 g de sel, couvert feu minimum 12–15 min, repos 5 min. Égrener.',
    'couper|courgettes|12||Creuser les courgettes|Courgettes lavées, non pelées, fendues en deux dans la longueur. Vider à la petite cuillère en laissant 8 mm de chair sur les bords et le fond. Pulpe hachée grossièrement, gardée. Saler l’intérieur des barques (une pincée chacune).',
    'couper|poivron, oignon, tomates|8||Tailler|Poivron sans côtes ni graines, dés de 1 cm. Oignon ciselé à 3 mm. Tomates épépinées, dés de 1 cm.',
    'saisir|oignon, poivron, pulpe, tomates, quinoa|10||Farce|Poêle, 2 c. à s. d’huile, feu moyen-vif. Oignon et poivron avec une pincée de sel 5 min. Pulpe de courgette 3 min : elle rend son eau, la laisser s’évaporer. Tomates 2 min. Feu coupé, quinoa, basilic ciselé, 8 g de sel, poivre. Goûter.||3,4,5',
    'dresser|courgettes, farce|8||Farcir|Sauce tomate (400 g) au fond d’un plat huilé. Barques dessus, farce tassée à la cuillère en dôme léger (≈ 100 g par demi-courgette).||4,6',
    'enfourner|courgettes farcies|33|P|Cuire au four|Couvert d’aluminium, 30–35 min à 190 °C : la pointe du couteau traverse la chair de la courgette sans forcer. Retirer l’aluminium les 5 dernières minutes pour dorer.|190',
    'refrigerer|courgettes farcies|40|P|Refroidir|Plat en cellule ou à découvert au frais, 10 °C à cœur en moins de 2 h.',
    'dresser|courgettes farcies|2|A|Dresser|Deux demi-courgettes par boîte, 2 c. à s. de sauce tomate autour. Opercule sans buée, étiquette.'] },

{ nom: 'Curry de légumes', code: 'VG', fichier: 'Curry de legumes végétarien VG',
  desc: 'Carottes, brocoli et pois chiches au lait de coco et pâte de curry, riz basmati.',
  ing: ['carotte|260|2 tasses en dés', 'brocoli|180|2 tasses de bouquets', 'pois chiches|250|1 boîte égouttée', 'lait de coco|400|1 boîte',
    'oignon|150|1', 'ail|10|2 gousses', 'pate de curry|30|2 c. à s.', 'huile olive|28|2 c. à s.', 'riz|1400|3 tasses (cru) → cuit', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, ail, carottes, brocoli|12||Tailler|Oignon ciselé à 3 mm. Ail dégermé, émincé. Carottes pelées en dés de 1 cm. Brocoli en fleurettes de 3 cm, tige pelée en rondelles.',
    'rincer|pois chiches|3||Rincer les pois chiches|Rincés 30 s à l’eau froide, égouttés.',
    'saisir|oignon, ail|5||Faire suer|Casserole, 1 c. à s. d’huile, feu moyen. Oignon avec une pincée de sel 5 min jusqu’à translucide, ail 30 s.',
    'melanger|pâte|3||Frire la pâte de curry|Prélever les 3 c. à s. de crème épaisse du dessus de la boîte de lait de coco, les ajouter avec la pâte de curry (30 g). Feu moyen, 2–3 min en remuant : l’huile rouge perle en surface et ça sent fort.||3',
    'saisir|carottes, brocoli|5||Enrober les légumes|Carottes et brocoli dans la pâte, 3–4 min en remuant pour enrober.||4',
    'mijoter|curry|18|P|Mijoter 15–20 min|Reste du lait de coco (≈ 350 g) et 100 ml d’eau chaude, pois chiches. Frémissement DOUX — jamais gros bouillons, le lait de coco trancherait — couvert, 15–20 min : carottes tendres au couteau, brocoli vert et tendre (l’ajouter à 8 min de la fin s’il est déjà en fleurettes petites). 8 g de sel, poivre, goûter.|88',
    'rincer|riz basmati|3||Rincer le riz|Bol, eau froide, frotter, vider ; 3–4 fois jusqu’à l’eau claire.',
    'bouillir|riz basmati|22||Cuire le riz basmati|1 volume de riz, 1,5 volume d’eau froide, 4 g de sel. Ébullition sans couvercle, couvercle, feu minimum 10–12 min, feu coupé 10 min couvert. Égrener, étaler.',
    'refrigerer|curry|40|P|Refroidir|Curry en bacs de 5 cm, riz sur plaque, 10 °C à cœur en moins de 2 h.',
    'dresser|curry + riz|2|A|Dresser|Tare. 230 g de riz, 250 g de curry avec sa sauce, séparés si possible. Opercule sans buée, étiquette.'] },

{ nom: 'Curry de poulet rôti, riz complet', code: 'PS', fichier: 'Curry de poulet  PS',
  desc: 'Poulet rôti en morceaux dans un curry au lait de coco, haricots verts et carottes, riz complet.',
  ing: ['poulet|900|900 g rôti désossé', 'oignon|300|2', 'ail|20|4 gousses', 'pate de curry|30|2 c. à s.', 'lait de coco|800|2 boîtes',
    'haricots verts|300|300 g', 'carotte|300|300 g', 'riz complet|1560|600 g (cru) → cuit', 'huile olive|56|4 c. à s.', 'sel|0|q.s.'],
  etapes: [
    'couper|oignons, ail, carottes, poulet|15||Tailler|Oignons ciselés à 3 mm. Ail dégermé, émincé. Carottes pelées en rondelles de 5 mm. Haricots verts équeutés, coupés en deux. Poulet en dernier, sur planche dédiée : cubes de 3 cm en travers des fibres. Laver planche, couteau et mains ensuite.',
    'assaisonner|poulet|3||Saler le poulet|9 g de sel, poivre, 15 min au frais. Sécher au papier avant la poêle.',
    'saisir|poulet|10||Dorer le poulet|Poêle chaude, 2 c. à s. d’huile, feu moyen-vif, 2 lots. 3 min sans toucher, retourner, 3 min : doré, encore rosé au centre (il finira dans la sauce). Réserver.',
    'saisir|oignons, ail|5||Faire suer|Même poêle, 1 c. à s. d’huile, feu moyen, oignons et pincée de sel 5 min, ail 30 s.',
    'melanger|pâte|3||Frire la pâte de curry|3 c. à s. de crème épaisse prélevée sur le lait de coco + pâte de curry (30 g), feu moyen 2–3 min : l’huile rouge perle, ça sent fort.||4',
    'mijoter|lait de coco|5|P|Mijoter la sauce|Reste du lait de coco (≈ 750 g), frémissement DOUX 5 min, jamais gros bouillons.|88|5',
    'mijoter|curry|12|P|Cuire poulet et légumes|Carottes 6 min, puis poulet et haricots verts 8–10 min à frémissement doux, couvert. Sonde : 74 °C dans le plus gros morceau de poulet. Carottes tendres au couteau. 8 g de sel, poivre.|74',
    'bouillir|riz complet|40||Cuire le riz complet|Rincé une fois. 1 volume de riz, 2 volumes d’eau, 4 g de sel : ébullition, couvercle, feu minimum 35–45 min, repos 10 min. (Ou comme des pâtes : grand volume d’eau salée, 30–35 min, égoutter.) Grain tendre avec de la mâche.',
    'refrigerer|curry|40|P|Refroidir|Curry en bacs de 5 cm, riz sur plaque, 10 °C à cœur en moins de 2 h.',
    'dresser|curry + riz|2|A|Dresser|Tare. 260 g de riz complet au fond, 300 g de curry avec sa sauce. Opercule sans buée, étiquette.'] },

{ nom: 'Dinde à la vapeur, légumes', code: 'PP', fichier: 'Dinde vapeur PP',
  desc: 'Poitrine de dinde et légumes cuits à la vapeur, sauce soja en option.',
  ing: ['dinde|1500|1,5 kg de poitrines', 'carotte|260|', 'haricots verts|260|', 'brocoli|260|6 tasses de légumes au total',
    'sauce soja|45|3 c. à s.', 'thym|0|q.s.', 'sel|0|q.s.'],
  etapes: [
    'assaisonner|dinde|4||Assaisonner la dinde|Filets aplatis à 2 cm d’épaisseur (cuisson régulière). 15 g de sel, poivre, thym effeuillé. 20 min au frais.',
    'bouillir|dinde|28|P|Cuire la dinde à la vapeur|Panier vapeur sur une eau qui bout franchement, couvercle fermé, filets sans qu’ils se touchent. 25–30 min. Sonde : 74 °C à cœur, chair blanche et opaque, jus clair.|74',
    'reposer|dinde|5|P|Reposer|Hors vapeur, couvert lâchement, 5 min : les jus se redistribuent.',
    'couper|carottes, haricots, brocoli|8||Tailler les légumes|Carottes en bâtonnets de 5 mm. Haricots équeutés. Brocoli en fleurettes de 3 cm.',
    'bouillir|légumes|7|P|Légumes à la vapeur|Même panier, eau à gros bouillons, couvercle. Carottes 7 min ; haricots et brocoli 5 min (les ajouter 2 min après les carottes). Vert VIF, pointe du couteau qui entre avec une légère résistance. Bain d’eau glacée 2 min, égoutter, sécher.||4',
    'refrigerer|dinde|30|P|Refroidir|Dinde et légumes étalés sur plaque, 10 °C à cœur en moins de 2 h.',
    'couper|dinde|4|A|Trancher la dinde|Tranches de 1 cm EN TRAVERS des fibres.',
    'dresser|dinde + légumes|2|A|Dresser|Tare. 220 g de dinde tranchée, 130 g de légumes. Sauce soja (1 c. à s.) dans un godet à part. Opercule sans buée, étiquette.'] },

{ nom: 'Filet de dinde grillé, citron confit', code: 'PM', fichier: 'Filet de dinde grillé au citrons confit PM',
  desc: 'Dinde marinée au citron, grillée, riz basmati, légumes vapeur, sauce vierge au citron confit.',
  ing: ['dinde|1080|6 filets', 'riz basmati|1560|600 g (cru) → cuit', 'brocoli|200|', 'carotte|200|', 'haricots verts|200|600 g de légumes au total',
    'huile olive|42|3 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: [
    'fouetter|huile, citron|3||Marinade|Cul-de-poule : jus de citron (80 g), 10 g de sel, poivre — fouetter 20 s, le sel fond dans l’acide. Huile (42 g) en filet en fouettant : ça épaissit et pâlit.',
    'refrigerer|dinde|30|P|Mariner 30 min|Filets aplatis à 2 cm dans un bac, marinade dessus, retournés pour enrober, filmés, 30 min à ≤ 4 °C. Pas plus d’1 h : l’acide raffermit la chair.||1',
    'rincer|riz basmati|3||Rincer le riz|Eau froide, frotter, vider ; 3–4 fois jusqu’à l’eau claire.',
    'bouillir|riz basmati|22||Cuire le riz|1 volume de riz, 1,5 d’eau froide, 4 g de sel. Ébullition, couvercle, feu minimum 10–12 min, feu coupé 10 min couvert. Égrener, étaler.',
    'saisir|dinde|14||Griller la dinde|Filets ÉGOUTTÉS et séchés au papier (la marinade brûle). Poêle chaude, feu moyen-vif, filet d’huile. 6–7 min sans toucher, retourner, 5–6 min. Sonde : 74 °C. Repos 5 min couvert lâchement.|74',
    'couper|brocoli, carotte, haricots verts|6||Tailler les légumes|Brocoli en fleurettes de 3 cm, carotte en bâtonnets de 5 mm, haricots équeutés. Garder les parures de carotte et de brocoli pour la sauce.',
    'bouillir|légumes|7|P|Légumes vapeur|Eau à gros bouillons, panier, couvercle. Carotte 7 min ; brocoli et haricots 5 min. Vert vif, légère résistance au couteau. Bain glacé 2 min, égoutter, sécher.||6',
    'melanger|sauce vierge|5||Sauce vierge|Parures de légumes en brunoise de 3 mm, zeste du citron râpé fin (jaune seulement), reste de jus de citron, 2 c. à s. d’huile, pincée de sel, poivre. Mélanger, 10 min de repos.||6',
    'refrigerer|dinde|30|P|Refroidir|Dinde, riz et légumes étalés sur plaque, 10 °C à cœur en moins de 2 h.',
    'dresser|dinde + riz + légumes|2|A|Dresser|Tare. 250 g de riz, un filet de dinde tranché en travers des fibres (180 g), 100 g de légumes, 1 c. à s. de sauce vierge sur la dinde. Opercule sans buée, étiquette.||4,7,8,9'] },

{ nom: 'Merlu en papillote', code: 'PP', fichier: 'Merlu en papillote PP',
  desc: 'Filet de merlu, tomate, citron et thym en papillote au four.',
  ing: ['merlu|900|6 filets', 'tomate|720|6', 'citron|100|1', 'thym|0|6 branches', 'huile olive|84|6 c. à s.', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer|200 °C, chaleur tournante, 15 min avant.|200',
    'couper|tomates, citron|6||Rondelles|Tomates en rondelles de 5 mm (couteau à dents). Citron lavé, rondelles de 3 mm, pépins retirés. Thym effeuillé.',
    'assaisonner|merlu|2||Saler le merlu|Filets séchés au papier, 9 g de sel, poivre.',
    'dresser|merlu, tomates, citron, thym|10||Monter les papillotes|6 rectangles de papier cuisson de 40 cm. Au centre de chacun : 3 rondelles de tomate, un filet de merlu (150 g), 2 rondelles de citron, thym, 1 c. à s. d’huile. Replier le papier en deux, puis rouler les trois bords sur eux-mêmes deux fois : fermeture HERMÉTIQUE, sinon la vapeur s’échappe et le poisson sèche.',
    'enfourner|papillotes de merlu|20|P|Cuire au four|Sur plaque, 200 °C, 18–22 min : les papillotes GONFLENT (c’est la vapeur). Ouvrir une papillote témoin en tenant le visage à l’écart : chair opaque qui se sépare en feuillets, sonde 63 °C.|200',
    'refrigerer|papillote|30|P|Refroidir|Papillotes OUVERTES sur plaque en cellule, 10 °C à cœur en moins de 2 h.',
    'dresser|papillote|2|A|Dresser|Le filet avec ses tomates et son jus de cuisson dans la boîte (le jus est la sauce), rondelle de citron dessus. Opercule sans buée, étiquette.'] },

{ nom: 'Merlu poché, brocoli, kale et mangue', code: 'PP', fichier: 'Merlu poché PP',
  desc: 'Merlu poché au vin blanc et bouquet garni, brocoli, chou kale, dés de mangue.',
  ing: ['merlu|900|6 filets', 'vin blanc|120|1/2 tasse', 'thym|0|bouquet garni', 'brocoli|300|300 g', 'mangue|250|1', 'chou kale|300|300 g'],
  etapes: [
    'couper|brocoli, kale, mangue|8||Tailler|Brocoli en fleurettes de 3 cm, tige pelée en rondelles. Kale : côte centrale retirée, feuilles roulées, rubans de 1 cm. Mangue : joues tranchées le long du noyau, quadrillées, retournées, dés de 1 cm.',
    'bouillir|court-bouillon|10||Court-bouillon|2 l d’eau, vin blanc (120 ml), 20 g de sel, thym, 6 grains de poivre. Ébullition 5 min pour infuser, puis BAISSER jusqu’au frémissement : quelques bulles, jamais gros bouillons.|85',
    'bouillir|merlu|9|P|Pocher le merlu|Filets (150 g) posés dans le liquide à 80–85 °C, couverts de liquide, feu doux. 8–10 min. Chair opaque qui se sépare en feuillets, sonde 63 °C. Sortir à l’écumoire large sur un torchon.|63|2',
    'bouillir|brocoli, kale|6||Blanchir les légumes|Grande casserole d’eau salée (10 g/l) à gros bouillons, SANS couvercle, bain glacé prêt à côté. Brocoli 3–4 min ; kale ajouté pour les 2 dernières minutes. Vert VIF, légère résistance au couteau. Bain glacé 2 min, égoutter, sécher.',
    'refrigerer|merlu|30|P|Refroidir|Merlu et légumes étalés sur plaque, 10 °C à cœur en moins de 2 h.',
    'dresser|merlu + légumes + mangue|2|A|Dresser|Tare. 100 g de légumes au fond, un filet de merlu (150 g) entier dessus, 40 g de dés de mangue à côté. Opercule sans buée, étiquette.'] },

{ nom: 'Natty wrap', code: 'PP', fichier: 'Natty wrap PP',
  desc: 'Tortilla complète, poulet grillé, poivron, carotte, concombre, sauce yaourt-citron.',
  ing: ['tortilla|360|6 tortillas', 'poulet|600|600 g grillé', 'poivron|150|1', 'carotte|120|1', 'concombre|300|1',
    'yaourt nature|120|1/2 tasse', 'jus de citron|30|2 c. à s.', 'menthe|5|q.s.', 'sel|0|q.s.'],
  etapes: [
    'fouetter|yaourt, citron|4||Sauce yaourt|Yaourt nature (120 g), jus de citron (30 g), 3 g de sel, poivre, menthe ciselée. Remuer à la CUILLÈRE 30 s — fouetté, le yaourt se liquéfie. 15 min au frais.',
    'couper|poivron, carotte, concombre|8||Tailler les légumes|Poivron sans côtes ni graines, peau contre la planche, lanières de 5 mm. Carotte en julienne de 3 mm × 5 cm. Concombre épépiné, bâtonnets de 5 mm × 6 cm, égouttés 10 min dans une passoire.',
    'couper|poulet|4||Tailler le poulet|Planche dédiée : blancs en lanières de 1 cm EN TRAVERS des fibres. Laver planche, couteau, mains.',
    'assaisonner|poulet|2||Saler le poulet|6 g de sel, poivre. Sécher au papier avant la poêle.',
    'saisir|poulet|8||Dorer le poulet|Poêle chaude, 1 c. à s. d’huile, feu moyen-vif, 2 lots. Lanières espacées, 2 min sans toucher, retourner, 2–3 min. Dorées, opaques à cœur, sonde 74 °C. Étaler sur plaque.|74',
    'refrigerer|poulet|30|P|Refroidir|Poulet étalé sur plaque, 10 °C à cœur en moins de 2 h. Le wrap se roule FROID.',
    'dresser|tortilla, poulet, légumes|3|A|Garnir|Tortilla à plat. Au centre, en bande : 100 g de poulet, 25 g de poivron, 20 g de carotte, 50 g de concombre. Laisser 4 cm libres de chaque côté.||2,6',
    'dresser|sauce yaourt|1|A|Sauce|2 c. à s. de sauce yaourt sur les légumes — pas plus, elle détremperait la tortilla.',
    'dresser|wrap|2|A|Rouler et couper|Rabattre les deux côtés, rouler serré depuis le bas. Couper en deux en biais. Un wrap par boîte, coupe vers le haut, étiquette.'] },

{ nom: 'Poulet à la moutarde, riz complet, légumes rôtis', code: 'PS', fichier: 'Poulet a la moutarde PS',
  desc: 'Cuisses de poulet badigeonnées de moutarde, rôties, riz complet, carottes et courgettes rôties.',
  ing: ['cuisse de poulet|1500|6 cuisses', 'moutarde|90|6 c. à s.', 'huile olive|56|4 c. à s.', 'thym|1|1 c. à c.',
    'riz complet|1560|600 g (cru) → cuit', 'carotte|300|', 'courgette|300|600 g de légumes au total', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer|200 °C, chaleur tournante, 15 min avant. Plaque des légumes DEDANS pour qu’elle soit chaude.|200',
    'assaisonner|poulet, moutarde|6||Badigeonner|Cuisses séchées au papier. 15 g de sel, poivre. Moutarde (90 g, soit 15 g par cuisse) au pinceau sur toute la surface, thym effeuillé. 20 min au frais si possible.',
    'saisir|poulet|8||Dorer le poulet|Poêle chaude, 2 c. à s. d’huile, feu moyen-vif. Cuisses côté peau 4 min sans toucher : peau dorée. Retourner 2 min. Dans le plat, peau dessus.',
    'couper|carottes, courgettes|8||Tailler les légumes|Carottes pelées en bâtonnets de 1 cm × 5 cm. Courgettes non pelées, tronçons de 2 cm. Saladier : 2 c. à s. d’huile, 6 g de sel, poivre, mélanger à la main — tout brille.',
    'enfourner|poulet|33|P|Rôtir le poulet|200 °C, 30–35 min. Légumes sur leur plaque chaude, une seule couche, espacés, les 15 dernières minutes. Poulet : sonde 74 °C près de l’os sans le toucher, peau brune et croustillante, jus clair. Légumes : bords dorés, couteau qui entre sans forcer.|74|1,3,4',
    'reposer|poulet|5|P|Reposer|5 min couvert lâchement.',
    'bouillir|riz complet|40||Cuire le riz complet|Rincé une fois. 1 volume, 2 volumes d’eau, 4 g de sel, couvercle, feu minimum 35–45 min, repos 10 min. Grain tendre avec de la mâche.',
    'refrigerer|poulet|40|P|Refroidir|Poulet, légumes et riz étalés, 10 °C à cœur en moins de 2 h.',
    'dresser|poulet + riz + légumes|2|A|Dresser|Tare. 260 g de riz complet, une cuisse, 100 g de légumes rôtis. Opercule sans buée, étiquette.'] },

{ nom: 'Poulet aux épinards, riz complet', code: 'PM', fichier: 'Poulet aux epinards PM',
  desc: 'Poitrine de poulet dorée, épinards à l’ail et muscade, riz complet.',
  ing: ['poulet|1080|6 poitrines', 'epinards|500|500 g frais', 'ail|20|4 gousses', 'huile olive|42|3 c. à s.', 'muscade|2|1 c. à c.',
    'riz complet|1560|600 g (cru) → cuit', 'sel|0|q.s.'],
  etapes: [
    'bouillir|riz complet|40||Cuire le riz complet|Rincé une fois. 1 volume, 2 volumes d’eau, 4 g de sel, couvercle, feu minimum 35–45 min, repos 10 min. Égrener, étaler.',
    'couper|ail|2||Émincer l’ail|Écrasé, pelé, dégermé, émincé à 1 mm.',
    'rincer|épinards|4||Laver les épinards|Deux bains d’eau froide, soulever, essorer À FOND : mouillés, ils bouillent dans la poêle.',
    'assaisonner|poulet|3||Saler le poulet|Blancs aplatis à 2 cm, séchés, 11 g de sel, poivre, 15 min au frais. Resécher.',
    'saisir|poulet|14||Dorer le poulet|Poêle chaude, 2 c. à s. d’huile, feu moyen-vif, 2 lots. 6–7 min sans toucher, retourner, 5–6 min. Sonde 74 °C, jus clair. Repos 5 min couvert lâchement, puis tranches de 1 cm en travers des fibres.|74',
    'saisir|épinards, ail|5||Tomber les épinards|Même poêle, reste d’huile, feu vif. Ail 30 s. Épinards par poignées, retournés à la pince dès que le dessous tombe, 1–2 min : 500 g deviennent une tasse. Muscade (2 g), 5 g de sel, poivre. Égoutter en pressant dans une passoire.||2,3,5',
    'refrigerer|poulet|30|P|Refroidir|Poulet, épinards et riz étalés, 10 °C à cœur en moins de 2 h.',
    'dresser|poulet + épinards + riz|2|A|Dresser|Tare. 260 g de riz d’un côté, 60 g d’épinards de l’autre, le poulet tranché (180 g) sur les épinards. Opercule sans buée, étiquette.'] },

{ nom: 'Poulet rôti aux légumes', code: 'SG', fichier: 'Poulet rôti aux légumes SG',
  desc: 'Cuisses de poulet rôties sur un lit de carottes, pommes de terre et courgettes.',
  ing: ['cuisse de poulet|1500|6 cuisses', 'carotte|500|', 'pomme de terre|500|', 'courgette|500|1,5 kg de légumes au total',
    'huile olive|56|4 c. à s.', 'herbes de provence|6|2 c. à s.', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer|200 °C, chaleur tournante, 15 min avant.|200',
    'assaisonner|poulet|4||Assaisonner le poulet|Cuisses séchées au papier. 15 g de sel, poivre, herbes de Provence (4 g), 2 c. à s. d’huile massées sur la peau. 30 min au frais à découvert : la peau sèche et croustillera.',
    'couper|carottes, pommes de terre, courgettes|15||Tailler les légumes|Carottes pelées en tronçons de 3 cm. Pommes de terre pelées en cubes de 2,5 cm, séchées au torchon. Courgettes en tronçons de 3 cm. Saladier : 2 c. à s. d’huile, 8 g de sel, herbes (2 g), poivre, mélanger à la main. Dans le plat en une seule couche.',
    'enfourner|poulet + légumes|45|P|Rôtir 45 min|Cuisses posées SUR les légumes, peau dessus. 200 °C, 40–45 min. Remuer les légumes à 25 min. Poulet : sonde 74 °C près de l’os, peau brune et croustillante, jus clair. Pommes de terre : couteau qui entre sans forcer, bords dorés.|74|1,2,3',
    'reposer|poulet|5|P|Reposer|5 min couvert lâchement.',
    'refrigerer|poulet rôti|40|P|Refroidir|Poulet et légumes étalés sur plaque, 10 °C à cœur en moins de 2 h.',
    'dresser|poulet rôti + légumes|2|A|Dresser|Tare. 250 g de légumes rôtis au fond, une cuisse dessus, 1 c. à s. du jus du plat. Opercule sans buée, étiquette.'] },

{ nom: 'Quinoa bowl, légumes grillés, sauce tahini', code: 'VG', fichier: 'Quinoa bowl VG',
  desc: 'Quinoa, courgettes, poivrons et aubergine rôtis, sauce tahini-citron.',
  ing: ['quinoa|765|1,5 tasse (cru) → cuit', 'courgette|400|2', 'poivron|300|2', 'aubergine|300|1', 'huile olive|56|1/4 tasse',
    'tahini|60|1/4 tasse', 'jus de citron|30|2 c. à s.', 'ail|5|1 gousse', 'sel|0|q.s.'],
  etapes: [
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, jusqu’à zéro mousse.',
    'bouillir|quinoa|15|P|Cuire le quinoa|1 volume, 2 volumes d’eau, 6 g de sel, couvert feu minimum 12–15 min, repos 5 min. Égrener, étaler pour refroidir.',
    'enfourner|four|10|P|Préchauffer|220 °C, chaleur tournante, plaque dedans.|220',
    'couper|courgettes, poivrons, aubergine|12||Tailler|Courgettes en rondelles de 1 cm. Poivrons sans côtes ni graines, lanières de 1,5 cm. Aubergine en cubes de 2 cm. Même calibre : même cuisson.',
    'huiler|légumes|3||Huiler et assaisonner|Saladier : légumes, 3 c. à s. d’huile, 8 g de sel, poivre, mélanger à la main : chaque morceau brille, pas de flaque.||4',
    'enfourner|légumes|25|P|Rôtir 20–25 min|Sur la plaque CHAUDE, papier cuisson, une seule couche, espacés (deux plaques s’il le faut). 220 °C, retourner à 12 min. Bords bruns, chair tendre, aubergine fondante.|220',
    'fouetter|tahini, citron, ail|4||Sauce tahini|Tahini (60 g), jus de citron (30 g), ail écrasé en pâte avec du sel : fouetter — ça se FIGE en bloc, c’est normal. Eau froide 1 c. à s. à la fois en fouettant (≈ 60 ml) jusqu’à une crème beige, lisse, nappante. 3 g de sel.',
    'refrigerer|légumes|30|P|Refroidir|Légumes sur plaque, quinoa étalé, 10 °C à cœur en moins de 2 h.',
    'dresser|quinoa + légumes + tahini|2|A|Monter le bowl|Tare. 380 g de quinoa au fond, 150 g de légumes rôtis dessus, sauce tahini (30 g) dans un godet à part ou en filet au dernier moment. Opercule sans buée, étiquette.'] },

{ nom: 'Risotto aux champignons', code: 'PS', fichier: 'Risotto aux champignons PS',
  desc: 'Riz arborio crémeux aux champignons et parmesan, persil.',
  ing: ['riz arborio|760|1,5 tasse (cru) → cuit', 'bouillon de legumes|1440|6 tasses', 'champignons|400|400 g', 'oignon|150|1',
    'huile olive|56|4 c. à s.', 'parmesan|50|1/2 tasse', 'beurre|30|2 c. à s.', 'persil|5|q.s.', 'sel|0|q.s.'],
  etapes: [
    'couper|champignons, oignon|8||Tailler|Champignons nettoyés à sec (jamais trempés), pied talé, lamelles de 3 mm. Oignon ciselé à 3 mm. Persil haché au dernier moment.',
    'bouillir|bouillon|8|P|Chauffer le bouillon|Bouillon de légumes (1,44 l) dans une casserole à côté, frémissant, une louche à portée : versé froid, il stopperait la cuisson à chaque ajout.|90',
    'saisir|champignons|7||Dorer les champignons|Poêle très chaude, 2 c. à s. d’huile, feu vif, champignons en une couche, 2 lots. 2–3 min sans remuer, puis 3 min : dorés, réduits de moitié, pas de flaque. Sel à la FIN. Réserver.',
    'saisir|oignon|5||Faire suer l’oignon|Rondeau, 2 c. à s. d’huile, feu moyen, oignon et pincée de sel 5 min jusqu’à translucide, sans coloration.',
    'melanger|riz arborio|2||Nacrer le riz|Riz arborio (760 g) NON rincé dans l’oignon, remuer 2 min : grains brillants, bords translucides, point blanc au centre.',
    'mijoter|risotto|18||Mouiller louche par louche|Une louche de bouillon chaud, remuer souvent à la spatule ; la suivante quand la précédente est absorbée (le fond se voit quand on trace un trait). 16–18 min. Al dente : ferme au centre. Champignons à 2 min de la fin.|90',
    'melanger|parmesan, beurre|2||Mantecare|HORS du feu : beurre froid en dés (30 g), parmesan râpé (50 g), remuer vivement 30 s. Couvrir 2 min. Il doit faire une vague quand on incline le rondeau. 8 g de sel, poivre, goûter.',
    'refrigerer|risotto|40|P|Refroidir|Étalé en bacs de 4 cm, cellule ou bain glacé, 10 °C à cœur en moins de 2 h. Il épaissit en refroidissant : c’est attendu.||7',
    'dresser|risotto|2|A|Dresser|Tare. 400 g de risotto, persil haché dessus au dernier moment. Opercule sans buée, étiquette.'] },

{ nom: 'Risotto de boulgour, petits pois et carottes', code: 'SG', fichier: 'Risotto de boulgour SG',
  desc: 'Boulgour cuit façon risotto au bouillon, petits pois, carottes, parmesan.',
  ing: ['boulgour|750|1,5 tasse (cru) → cuit', 'bouillon de legumes|960|4 tasses', 'petits pois|150|1 tasse', 'carotte|240|2', 'oignon|150|1',
    'huile olive|56|4 c. à s.', 'parmesan|50|1/2 tasse', 'sel|0|q.s.'],
  etapes: [
    'couper|carottes, oignon|6||Tailler|Carottes pelées en dés de 5 mm (petits : elles cuisent dans le boulgour). Oignon ciselé à 3 mm.',
    'bouillir|bouillon|8|P|Chauffer le bouillon|Bouillon (960 ml) frémissant dans une casserole à côté.|90',
    'saisir|oignon|5||Faire suer|Rondeau, 2 c. à s. d’huile, feu moyen, oignon et pincée de sel 5 min : translucide.',
    'mijoter|boulgour|12||Mouiller louche par louche|Boulgour (750 g) 1 min dans l’oignon pour l’enrober, puis bouillon chaud par louches en remuant, 10–12 min : grains gonflés, encore fermes.|90',
    'mijoter|petits pois, carottes|8||Finir la cuisson|Carottes ajoutées à mi-cuisson du boulgour (6 min), petits pois pour les 3 dernières minutes. Tendres, petits pois vert vif. Reste du bouillon si ça sèche.||1,4',
    'melanger|parmesan|2||Parmesan|Hors du feu, parmesan râpé (50 g), 6 g de sel, poivre, remuer, couvrir 3 min.',
    'refrigerer|risotto de boulgour|40|P|Refroidir|Bacs de 4 cm, 10 °C à cœur en moins de 2 h.||6',
    'dresser|risotto de boulgour|2|A|Dresser|Tare. 350 g par boîte. Opercule sans buée, étiquette.'] },

{ nom: 'Salade de lentilles', code: 'VG', fichier: 'Salade de lentille VG',
  desc: 'Lentilles vertes, concombre, poivron, carotte, oignon rouge, pignons, vinaigrette moutarde-cidre.',
  ing: ['lentilles|400|2 tasses cuites', 'concombre|300|1', 'poivron rouge|150|1', 'carotte|120|1', 'oignon rouge|75|1/2',
    'pignons de pin|45|1/3 tasse', 'huile olive|84|6 c. à s.', 'vinaigre de cidre|30|2 c. à s.', 'moutarde|5|1 c. à c.', 'persil|10|1/4 tasse', 'sel|0|q.s.'],
  etapes: [
    'couper|concombre, poivron, carotte, oignon rouge, persil|12||Tailler|Concombre épépiné, dés de 1 cm, 10 min en passoire. Poivron sans côtes, dés de 1 cm. Carotte pelée, râpée gros. Oignon rouge ciselé fin, 10 min à l’eau froide, égoutté. Persil lavé, ESSORÉ, haché en trois passes.',
    'saisir|pignons|3||Griller les pignons|Poêle SÈCHE, feu doux-moyen, 2–3 min en secouant sans arrêt. Dès l’odeur de grillé et blond clair : verser aussitôt dans une assiette froide, ils finissent de dorer seuls.',
    'fouetter|huile, vinaigre, moutarde|3||Vinaigrette|Vinaigre de cidre (30 g), moutarde (5 g), 6 g de sel, poivre : fouetter 20 s. Huile (84 g) en filet mince en fouettant 40 s : elle épaissit et pâlit. Goûter sur une lentille.',
    'melanger|lentilles, légumes|4||Assembler|Lentilles cuites, égouttées et FROIDES. Légumes, en soulevant à la maryse. Vinaigrette au moment du dressage, ou dans un godet si la salade attend.',
    'dresser|salade de lentilles|2|A|Dresser|Tare. 320 g de salade, 20 g de vinaigrette en godet (ou mélangée si livrée le jour même), pignons (8 g) et persil sur le dessus. Opercule, étiquette.'] },

{ nom: 'Salade de poulet grillé', code: 'PP', fichier: 'Salade de poulet  grillé 2 PP',
  desc: 'Poitrine de poulet grillée sur laitue, tomates cerises et concombre, vinaigrette balsamique.',
  ing: ['poulet|1080|6 poitrines', 'laitue|300|300 g', 'tomates cerises|300|300 g', 'concombre|300|1',
    'huile olive|84|6 c. à s.', 'vinaigre balsamique|45|3 c. à s.', 'sel|0|q.s.'],
  etapes: [
    'assaisonner|poulet|3||Assaisonner|Blancs aplatis à 2 cm, séchés, 11 g de sel, poivre, 15 min au frais. Resécher au papier.',
    'saisir|poulet|14||Griller le poulet|Poêle chaude, filet d’huile, feu moyen-vif, 2 lots. 6–7 min sans toucher, retourner, 5–6 min. Sonde 74 °C, jus clair.|74',
    'reposer|poulet|8|P|Laisser tiédir|Couvert lâchement, 8 min : les jus se redistribuent.',
    'couper|tomates cerises, concombre, poulet|8||Tailler|Tomates cerises en deux. Concombre en rondelles de 3 mm, égouttées 10 min. Laitue lavée en deux bains, essorée, déchirée à la main en morceaux de 4 cm. Poulet en tranches de 1 cm EN TRAVERS des fibres.',
    'fouetter|huile, balsamique|2||Vinaigrette|Balsamique (45 g), 6 g de sel, poivre, fouetter 20 s ; huile (84 g) en filet en fouettant 40 s.',
    'refrigerer|poulet|30|P|Refroidir|Poulet tranché étalé sur plaque, 10 °C à cœur en moins de 2 h. Une salade se monte FROIDE.',
    'dresser|salade + poulet|2|A|Dresser|Tare. Laitue au fond (50 g), concombre et tomates (100 g), poulet tranché (180 g) dessus. Vinaigrette (20 g) en godet à part : mélangée, la laitue serait fanée à la livraison. Opercule, étiquette.||5,6'] },

{ nom: 'Salade de poulet grillé, vinaigrette avocat-citron', code: 'PS', fichier: 'Salade de poulet grillé avocat citron PS',
  desc: 'Poulet grillé, laitue, concombre, tomates cerises et une vinaigrette crémeuse à l’avocat.',
  ing: ['poulet|540|3 poitrines', 'laitue|300|300 g', 'concombre|300|1', 'tomates cerises|300|300 g', 'avocat|340|2',
    'huile olive|56|4 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: [
    'assaisonner|poulet|3||Assaisonner|Blancs aplatis à 2 cm, séchés, 6 g de sel, poivre, 15 min au frais. Resécher.',
    'saisir|poulet|14||Griller le poulet|Poêle chaude, filet d’huile, feu moyen-vif. 6–7 min sans toucher, retourner, 5–6 min. Sonde 74 °C.|74',
    'reposer|poulet|8|P|Laisser tiédir|Couvert lâchement, 8 min.',
    'couper|concombre, tomates cerises, poulet|8||Tailler|Concombre en rondelles de 3 mm, égouttées. Tomates cerises en deux. Laitue lavée, essorée, déchirée. Poulet en tranches de 1 cm en travers des fibres.',
    'mixer|avocats|4||Vinaigrette avocat|Chair de 2 avocats, jus de citron (80 g) AUSSITÔT, huile (56 g), 6 g de sel, poivre. Mixer 30 s au plongeant jusqu’à lisse ; détendre à l’eau froide (2–4 c. à s.) jusqu’à consistance nappante. Film au contact.',
    'refrigerer|poulet|30|P|Refroidir|Poulet étalé, 10 °C à cœur en moins de 2 h.',
    'dresser|salade + poulet + vinaigrette|2|A|Dresser|Tare. Laitue (50 g), concombre et tomates (100 g), poulet (90 g), vinaigrette avocat (60 g) en godet à part. Opercule, étiquette.||5,6'] },

{ nom: 'Salade de quinoa', code: 'VG', fichier: 'Salade de quinoa VG',
  desc: 'Quinoa, concombre, tomates, poivron, oignon rouge, avocat, coriandre, citron.',
  ing: ['quinoa|765|1,5 tasse (cru) → cuit', 'concombre|300|1', 'tomate|240|2', 'poivron rouge|150|1', 'oignon rouge|75|1/2',
    'avocat|340|2', 'coriandre|10|1/4 tasse', 'huile olive|84|6 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: [
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, jusqu’à zéro mousse.',
    'bouillir|quinoa|15|P|Cuire le quinoa|1 volume, 2 volumes d’eau, 6 g de sel, couvercle, feu minimum 12–15 min. Anneau blanc visible sur chaque grain.',
    'reposer|quinoa|10|P|Reposer et refroidir|5 min hors du feu couvert, égrener à la fourchette, puis étaler sur plaque : la salade se monte sur un quinoa FROID, sinon les herbes fanent et l’avocat brunit.',
    'couper|concombre, tomates, poivron, oignon rouge, avocats, coriandre|14||Tailler|Concombre épépiné, dés de 1 cm, égoutté. Tomates épépinées, dés de 1 cm. Poivron sans côtes, dés de 1 cm. Oignon rouge ciselé fin, 10 min à l’eau froide. Avocats en dés de 1,5 cm, citronnés AUSSITÔT. Coriandre hachée en dernier.',
    'fouetter|huile, citron|2||Vinaigrette|Jus de citron (80 g), 8 g de sel, poivre, fouetter 20 s ; huile (84 g) en filet en fouettant 40 s.',
    'melanger|quinoa, légumes|4||Assembler|Quinoa froid égrené, légumes, avocat en dernier, en soulevant à la maryse — pas en tournant. Vinaigrette, deux mouvements, goûter.||3,4',
    'dresser|salade de quinoa|2|A|Dresser|Tare. 400 g par boîte, coriandre sur le dessus. Opercule, étiquette.'] },

{ nom: 'Salade de millet aux agrumes', code: 'SG', fichier: 'Salade millet aux agrumes SG',
  desc: 'Millet, orange, pamplemousse, amandes effilées, raisins secs, vinaigrette au cidre.',
  ing: ['millet|900|1,5 tasse (cru) → cuit', 'orange|360|2', 'pamplemousse|300|1', 'amandes effilees|30|1/4 tasse', 'raisins secs|40|1/4 tasse',
    'huile olive|56|1/4 tasse', 'vinaigre de cidre|45|3 c. à s.', 'sel|0|q.s.'],
  etapes: [
    'rincer|millet|2||Rincer le millet|Passoire fine, eau froide, 30 s.',
    'bouillir|millet|18|P|Cuire le millet|Facultatif : 2 min à sec dans la casserole pour toaster (odeur de noisette). 1 volume, 2,5 volumes d’eau, 6 g de sel. Ébullition, couvercle, feu minimum 15–18 min.',
    'reposer|millet|10|P|Reposer et refroidir|10 min hors du feu couvert, égrener, étaler sur plaque jusqu’à froid.',
    'couper|oranges, pamplemousse|8||Peler à vif les agrumes|Pôles coupés, poser à plat, peler à vif en suivant la courbe pour retirer TOUTE la partie blanche (amère). Au-dessus d’un bol, lever les quartiers entre les membranes. Presser les membranes : le jus va dans la vinaigrette. Quartiers coupés en deux.',
    'saisir|amandes|3||Griller les amandes|Poêle SÈCHE, feu doux-moyen, 2–3 min en secouant : blond clair, odeur de grillé. Verser aussitôt dans une assiette froide.',
    'melanger|raisins|10|P|Réhydrater les raisins|Raisins secs 10 min dans le jus d’agrumes récupéré, égouttés (garder le jus).||4',
    'fouetter|huile, vinaigre|2||Vinaigrette|Vinaigre de cidre (45 g), jus d’agrumes, 6 g de sel, poivre, fouetter ; huile (56 g) en filet.||4,6',
    'melanger|millet, agrumes, amandes, raisins|4||Assembler|Millet froid égrené, raisins, agrumes en dernier en soulevant (ils s’écrasent). Vinaigrette, goûter.||3,4,5,6,7',
    'dresser|salade de millet|2|A|Dresser|Tare. 300 g par boîte, amandes (5 g) sur le dessus au dernier moment pour qu’elles croquent. Opercule, étiquette.'] },

{ nom: 'Saumon aux amandes, quinoa, asperges', code: 'PS', fichier: 'Saumon grillé aux amandes PS',
  desc: 'Filet de saumon en croûte d’amandes au citron, quinoa et asperges vapeur.',
  ing: ['saumon|900|6 filets', 'amandes effilees|150|1,5 tasse', 'huile olive|56|4 c. à s.', 'citron|60|1 (jus et zeste)',
    'quinoa|1530|3 tasses (cru) → cuit', 'asperges|450|1,5 botte', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer|180 °C, chaleur tournante, 15 min avant.|180',
    'melanger|amandes, citron|3||Croûte d’amandes|Amandes effilées (150 g), zeste du citron râpé fin (jaune seulement), 1 c. à s. de jus, 3 g de sel, 2 c. à s. d’huile : mélanger, les amandes doivent être juste humides.',
    'assaisonner|saumon|3||Saler le saumon|Pavés (150 g) séchés au papier, 9 g de sel, poivre, filet d’huile.',
    'dresser|saumon, amandes|5||Recouvrir le saumon|Pavés sur plaque + papier cuisson, espacés de 3 cm. Croûte d’amandes pressée sur le dessus de chaque pavé (25 g).',
    'enfourner|saumon|15|P|Cuire au four|180 °C, 12–15 min. Amandes dorées. Sonde au plus épais : 63 °C — la chair est rose opaque et se sépare en feuillets. Si beaucoup de blanc perle en surface, c’est déjà trop : sortir.|63',
    'rincer|quinoa|2||Rincer le quinoa|Passoire fine, eau froide, jusqu’à zéro mousse.',
    'bouillir|quinoa|15||Cuire le quinoa|1 volume, 2 volumes d’eau, 8 g de sel, couvercle, feu minimum 12–15 min, repos 5 min. Égrener, étaler.',
    'couper|asperges|4||Préparer les asperges|Plier la base : elle casse d’elle-même où elle devient fibreuse. Éplucher le tiers bas des grosses. Tronçons de 4 cm en biseau.',
    'bouillir|asperges|5|P|Blanchir les asperges|Eau salée (10 g/l) à gros bouillons, sans couvercle, bain glacé prêt. 3–5 min selon la grosseur : vert vif, légère résistance. Bain glacé 2 min, égoutter, sécher.',
    'refrigerer|saumon|30|P|Refroidir|Saumon, quinoa, asperges étalés, 10 °C à cœur en moins de 2 h.',
    'dresser|saumon + quinoa + asperges|2|A|Dresser|Tare. 250 g de quinoa, 75 g d’asperges, un pavé de saumon avec sa croûte dessus. Opercule sans buée, étiquette.'] },

{ nom: 'Sauté de légumes au tofu, riz', code: 'SG', fichier: 'Sauté de légumes SG',
  desc: 'Tofu doré, carottes, brocoli et poivrons sautés au gingembre, ail et sauce soja, riz.',
  ing: ['carotte|480|4', 'brocoli|400|1', 'poivron|300|2', 'tofu|400|400 g ferme', 'sauce soja|60|4 c. à s.', 'huile olive|42|3 c. à s.',
    'ail|10|2 gousses', 'gingembre|8|1 c. à s. râpé', 'riz|1560|600 g (cru) → cuit'],
  etapes: [
    'refrigerer|tofu|25|P|Presser le tofu|Bloc entre deux torchons, planche et poids d’1 kg dessus, 20–30 min : il perd 60–100 g d’eau. Sans ça, il colle et ne dore pas.',
    'couper|carottes, brocoli, poivrons, tofu, ail, gingembre|14||Tailler|Carottes en rondelles de 3 mm en biseau. Brocoli en fleurettes de 3 cm. Poivrons en lanières de 1 cm. Tofu pressé en cubes de 2,5 cm, séchés. Ail dégermé, émincé. Gingembre pelé à la cuillère, râpé fin.',
    'rincer|riz|3||Rincer le riz|Eau froide, 3–4 fois jusqu’à l’eau claire.',
    'bouillir|riz|22||Cuire le riz|1 volume, 1,5 d’eau froide, 4 g de sel, couvercle feu minimum 10–12 min, feu coupé 10 min couvert. Égrener, étaler.',
    'saisir|tofu|10||Dorer le tofu|Wok ou poêle antiadhésive, 2 c. à s. d’huile, feu moyen-vif. Cubes espacés, 3–4 min SANS toucher : ils se décollent seuls quand la croûte est là. Retourner face par face, 2 min chacune. Réserver.',
    'saisir|carottes, brocoli, poivrons|7||Sauter les légumes|Même wok, feu VIF, reste d’huile. Carottes 2 min, brocoli 2 min, poivrons 2 min, en remuant par secousses. Ail et gingembre 30 s. 2 c. à s. d’eau, couvercle 1 min : le brocoli finit à la vapeur. Vert vif, croquant.',
    'melanger|tofu, sauce soja|2||Remettre le tofu|Feu coupé. Tofu, sauce soja (60 g) versée hors du feu (sur le feu elle brûle), enrober 30 s. Goûter : la sauce soja sale.||5,6',
    'refrigerer|sauté|30|P|Refroidir|Sauté et riz étalés, 10 °C à cœur en moins de 2 h.||4,7',
    'dresser|sauté + riz|2|A|Dresser|Tare. 260 g de riz au fond, 250 g de sauté dessus. Opercule sans buée, étiquette.'] },

{ nom: 'Sauté de légumes et tofu, riz basmati', code: 'SG', fichier: 'Sauté de légumes au tofu SG',
  desc: 'Tofu ferme doré au wok, légumes sautés au gingembre, sauce soja, riz basmati.',
  ing: ['tofu|600|600 g ferme', 'brocoli|130|', 'carotte|130|', 'poivron|130|3 tasses de légumes au total', 'sauce soja|60|4 c. à s.',
    'huile olive|42|3 c. à s.', 'ail|10|2 gousses', 'gingembre|6|2 c. à c. râpé', 'riz basmati|1300|~500 g (cru) → cuit'],
  etapes: [
    'refrigerer|tofu|25|P|Presser le tofu|Bloc entre deux torchons sous une planche et un poids, 20–30 min.',
    'couper|tofu, légumes, ail, gingembre|12||Tailler|Tofu pressé en cubes de 2,5 cm, séchés. Brocoli en fleurettes de 3 cm, carotte en rondelles de 3 mm en biseau, poivron en lanières de 1 cm. Ail émincé, gingembre râpé.',
    'rincer|riz basmati|3||Rincer le riz|Eau froide, 3–4 fois jusqu’à l’eau claire.',
    'bouillir|riz basmati|22||Cuire le riz|1 volume, 1,5 d’eau froide, 4 g de sel, couvercle feu minimum 10–12 min, feu coupé 10 min couvert. Égrener, étaler.',
    'saisir|tofu|10||Dorer le tofu|Wok, 2 c. à s. d’huile, feu moyen-vif, cubes espacés, 3–4 min sans toucher par face, 4 faces. Réserver.',
    'saisir|légumes|7||Sauter les légumes|Feu vif, reste d’huile : carotte 2 min, brocoli 2 min, poivron 2 min ; ail et gingembre 30 s ; 2 c. à s. d’eau et couvercle 1 min. Vert vif, croquant.',
    'mijoter|tofu, sauce soja|3||Finir|Tofu remis, sauce soja (60 g), feu DOUX 2 min pour enrober — pas plus, elle caramélise et amertume.||5,6',
    'refrigerer|sauté|30|P|Refroidir|Sauté et riz étalés, 10 °C à cœur en moins de 2 h.||4,7',
    'dresser|sauté + riz|2|A|Dresser|Tare. 220 g de riz, 220 g de sauté. Opercule sans buée, étiquette.'] },

{ nom: 'Soupe de lentilles corail, épinards et carottes', code: 'SG', fichier: 'Soupe de lentilles rouges SG',
  desc: 'Lentilles corail mijotées au bouillon et cumin, épinards, filet de citron.',
  ing: ['lentilles corail|780|1,5 tasse (cru) → cuit', 'oignon|150|1', 'carotte|240|2', 'bouillon de legumes|960|4 tasses', 'epinards|90|3 tasses',
    'huile olive|28|2 c. à s.', 'cumin|2|1 c. à c.', 'citron|40|q.s.', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, carottes|6||Tailler|Oignon ciselé à 3 mm. Carottes pelées en dés de 1 cm.',
    'rincer|lentilles corail|3||Rincer les lentilles|Passoire fine, eau froide, remuer à la main jusqu’à l’eau claire (l’amidon fait mousser la cuisson).',
    'saisir|oignon, carottes|6||Faire suer|Casserole, 2 c. à s. d’huile, feu moyen, oignon et carottes avec une pincée de sel, 5–6 min : oignon translucide.',
    'melanger|cumin|1||Fleurir le cumin|Cumin (2 g) dans le gras chaud, 30 s en remuant : le parfum monte.',
    'mijoter|lentilles, bouillon|20|P|Mijoter 20 min|Lentilles corail, bouillon CHAUD (960 ml) et 500 ml d’eau chaude (les lentilles corail boivent 3 volumes). Ébullition, puis frémissement, couvercle entrouvert, 15–20 min en remuant toutes les 5 min (elles attachent). Elles se défont et lient la soupe d’elles-mêmes : c’est voulu.|90|2,4',
    'mijoter|épinards|3||Épinards|Épinards lavés et essorés, dans la dernière minute : ils fondent. 10 g de sel, poivre, goûter.',
    'mixer|soupe|4||Mixer (optionnel)|Plongeant, tête au fond avant de démarrer, 30 s pour un velouté lisse — ou quelques secondes pour garder les dés de carotte. Détendre à l’eau chaude si trop épaisse. Jus de citron (40 g) après mixage, regoûter.',
    'refrigerer|soupe de lentilles|40|P|Refroidir|Bacs de 5 cm ou bain glacé en remuant, 10 °C à cœur en moins de 2 h.',
    'dresser|soupe de lentilles|2|A|Dresser|Tare. 450 g par boîte, filet de citron. Opercule sans buée, étiquette.'] },

{ nom: 'Soupe de légumes', code: 'VG', fichier: 'Soupe de légumes VG',
  desc: 'Carottes, céleri, pommes de terre, courgette, haricots et tomates au bouillon, herbes de Provence.',
  ing: ['oignon|150|1', 'carotte|240|2', 'celeri|100|2 branches', 'pomme de terre|540|3', 'courgette|200|1', 'haricots blancs|250|1 boîte égouttée',
    'tomates concassees|400|1 boîte', 'bouillon de legumes|1440|6 tasses', 'huile olive|28|2 c. à s.', 'herbes de provence|2|1 c. à c.', 'persil|5|q.s.', 'sel|0|q.s.'],
  etapes: [
    'couper|oignon, carottes, céleri, pommes de terre, courgette|15||Tailler|Oignon ciselé à 5 mm. Carottes pelées, dés de 1 cm. Céleri effilé, dés de 1 cm. Pommes de terre pelées, dés de 1,5 cm, sous l’eau froide. Courgette non pelée, dés de 1,5 cm.',
    'saisir|oignon, carottes, céleri|5||Faire suer|Marmite, 2 c. à s. d’huile, feu moyen, oignon, carottes, céleri, pincée de sel, 5 min : oignon translucide, sans coloration.',
    'melanger|pommes de terre, courgette, haricots, tomates, bouillon|3||Mouiller|Pommes de terre égouttées, tomates concassées (400 g), bouillon CHAUD (1,44 l) : le liquide doit couvrir de 2 cm. Herbes de Provence (2 g), 8 g de sel, poivre. Courgette et haricots blancs rincés : gardés pour les 8 dernières minutes.||1,2',
    'mijoter|soupe|23|P|Mijoter 20–25 min|Ébullition, puis frémissement, couvercle entrouvert. À 12 min : courgette et haricots. Prêt quand la pointe du couteau traverse une pomme de terre sans forcer. Goûter, rectifier le sel.|90',
    'mixer|soupe|4||Mixer partiellement (optionnel)|Plongeant, 3 impulsions de 2 s pour lier sans tout réduire — ou 30 s pour un velouté. Détendre au bouillon chaud si trop épais.',
    'refrigerer|soupe de légumes|40|P|Refroidir|Bacs de 5 cm ou bain glacé en remuant, 10 °C à cœur en moins de 2 h.',
    'dresser|soupe de légumes|2|A|Dresser|Tare. 500 g par boîte, persil haché dessus. Opercule sans buée, étiquette.'] },

{ nom: 'Thon grillé, salsa de mangue, riz sauvage', code: 'PS', fichier: 'Steak de thon salsa mango PS (1)',
  desc: 'Steak de thon grillé, salsa fraîche mangue-oignon rouge-coriandre, riz sauvage.',
  ing: ['thon|900|6 steaks', 'mangue|500|2', 'oignon rouge|150|1', 'piment|10|1 jalapeño', 'coriandre|20|1/2 tasse',
    'jus de citron|60|4 c. à s.', 'riz sauvage|1200|~460 g (cru) → cuit', 'sel|0|q.s.'],
  etapes: [
    'couper|mangues, oignon rouge, piment, coriandre|10||Tailler la salsa|Mangues : joues tranchées le long du noyau, quadrillées, retournées, dés de 1 cm. Oignon rouge ciselé fin, 10 min à l’eau froide. Piment fendu, membranes blanches et graines retirées (c’est là qu’est le piquant), émincé à 2 mm — mains lavées au savon après. Coriandre hachée en dernier.',
    'melanger|salsa de mangue|3||Salsa|Mangue, oignon, la MOITIÉ du piment, coriandre, jus de citron (60 g), 4 g de sel. Mélanger doucement, 10 min de repos, goûter : acide net. Ajouter du piment si besoin.',
    'bouillir|riz sauvage|50||Cuire le riz sauvage|1 volume de riz, 3 volumes d’eau, 8 g de sel. Ébullition, couvercle entrouvert, feu doux, 45–55 min : les grains éclatent et montrent leur intérieur clair. Égoutter le surplus, étaler.',
    'assaisonner|thon|2||Saler le thon|Steaks (150 g, 2–3 cm) séchés au papier, 9 g de sel, poivre, filet d’huile. Juste avant la poêle.',
    'saisir|thon|6||Griller le thon|Poêle TRÈS chaude, feu vif. 60–90 s par face : croûte marquée, bord blanc de 1 cm, centre rosé (50–55 °C). Pour un plat livré et réchauffé, viser 60 °C au plus — au-delà le thon est sec et gris. Le dire sur l’étiquette : « à réchauffer doucement ».|60',
    'refrigerer|thon|30|P|Refroidir|Thon sur plaque, riz étalé, 10 °C à cœur en moins de 2 h.',
    'dresser|thon + salsa + riz|2|A|Dresser|Tare. 200 g de riz sauvage, un steak de thon, 100 g de salsa en godet à part (elle rendrait son jus sur le riz). Opercule sans buée, étiquette.'] },

{ nom: 'Taboulé de lentilles et tofu aux herbes', code: 'VG', fichier: 'Taboulé de lentilles et tofu aux herbes',
  desc: 'Lentilles, boulgour, tofu doré, concombre, tomates, menthe et persil, citron.',
  ing: ['lentilles|200|1 tasse cuites', 'tofu|300|300 g', 'boulgour|280|1 tasse cuit', 'concombre|300|1', 'tomate|240|2', 'oignon rouge|75|1/2',
    'menthe|10|1/4 tasse', 'persil|10|1/4 tasse', 'huile olive|56|4 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: [
    'refrigerer|tofu|25|P|Presser le tofu|Bloc entre deux torchons sous une planche et un poids, 20–30 min.',
    'bouillir|boulgour|12|P|Hydrater le boulgour|Boulgour fin (280 g) dans un saladier, 1 volume d’eau bouillante salée (4 g), couvrir, 10 min. Égrener à la fourchette, étaler pour refroidir.',
    'couper|tofu, concombre, tomates, oignon rouge, menthe, persil|12||Tailler|Tofu pressé en dés de 2 cm, séchés. Concombre épépiné, dés de 1 cm, égoutté. Tomates épépinées, dés de 1 cm. Oignon rouge ciselé fin, 10 min à l’eau froide. Menthe et persil lavés, ESSORÉS, hachés en dernier — trois passes, pas plus.',
    'saisir|tofu|8||Dorer le tofu|Poêle antiadhésive, 2 c. à s. d’huile, feu moyen-vif, dés espacés, 3 min sans toucher par face, croustillant sur 4 faces. Étaler pour refroidir.',
    'fouetter|huile, citron|2||Vinaigrette|Jus de citron (80 g), 8 g de sel, poivre, fouetter 20 s ; reste d’huile (≈ 30 g) en filet.',
    'melanger|lentilles, boulgour, légumes, herbes|4||Assembler|Lentilles cuites égouttées et froides, boulgour froid, légumes, herbes en dernier, en soulevant. Vinaigrette, goûter : un taboulé doit être franchement acide et herbacé.||2,3',
    'dresser|taboulé + tofu|2|A|Dresser|Tare. 300 g de taboulé, 50 g de tofu doré sur le dessus (pas mélangé : il resterait croustillant). Opercule, étiquette.||4,5,6'] },

{ nom: 'Tacos de poisson', code: 'PP', fichier: 'Tacos de poisson PP',
  desc: 'Poisson blanc poêlé, tortilla de maïs, chou émincé, avocat, sauce yaourt-citron, coriandre.',
  ing: ['merlu|900|6 filets de poisson blanc', 'tortilla mais|360|6', 'chou|500|1/2', 'avocat|340|2', 'yaourt nature|120|1/2 tasse',
    'jus de citron|30|2 c. à s.', 'coriandre|10|q.s.', 'huile olive|14|un peu', 'sel|0|q.s.'],
  etapes: [
    'couper|chou, avocats, coriandre|10||Tailler|Chou : trognon retiré, émincé à 2 mm à la mandoline (garde-main), 3 g de sel, 15 min en passoire, pressé. Avocats en dés de 1,5 cm, citronnés aussitôt. Coriandre hachée en dernier.',
    'fouetter|yaourt, citron|3||Sauce yaourt|Yaourt (120 g), jus de citron (30 g), 3 g de sel, poivre, à la cuillère 30 s.',
    'assaisonner|poisson|3||Saler le merlu|Filets séchés au papier, 9 g de sel, poivre, 5 min, resécher.',
    'saisir|poisson|10||Cuire le poisson|Poêle chaude, 1 c. à s. d’huile, feu moyen-vif. Filets posés en s’éloignant de soi, 4 min sans toucher (la chair devient opaque en montant sur le côté), un seul retournement, 1–2 min. Sonde 63 °C. Effeuiller grossièrement à la fourchette.|63',
    'refrigerer|poisson|30|P|Refroidir|Poisson effeuillé étalé sur plaque, 10 °C à cœur en moins de 2 h.',
    'saisir|tortillas|4|A|Chauffer les tortillas|Poêle sèche, feu vif, 20–30 s par face : cloques et taches brunes. Sous un torchon.',
    'dresser|tacos|3|A|Monter les tacos|Par boîte, 2 tortillas à plat : 75 g de poisson chacune, 40 g de chou, 25 g d’avocat, coriandre. Sauce yaourt (20 g) en godet à part — sur la tortilla elle la détremperait. Tacos pliés en deux côte à côte. Opercule, étiquette.'] },

{ nom: 'Truite aux herbes', code: 'PM', fichier: 'Truite aux herbes fine PM',
  desc: 'Filet de truite au four, citron, ciboulette et persil, légumes vapeur.',
  ing: ['truite|900|6 filets', 'huile olive|84|6 c. à s.', 'citron|100|1', 'ciboulette|10|1/4 tasse', 'persil|10|1/4 tasse', 'legumes|600|vapeur, pour accompagner', 'sel|0|q.s.'],
  etapes: [
    'enfourner|four|10|P|Préchauffer|200 °C, chaleur tournante, 15 min avant.|200',
    'couper|citron, ciboulette, persil|5||Tailler|Citron lavé, rondelles de 3 mm sans pépins. Ciboulette aux ciseaux (3 mm). Persil lavé, essoré, haché en trois passes.',
    'huiler|truite|4||Préparer la plaque|Filets séchés au papier (la peau surtout). Plaque + papier cuisson, filets peau dessous, espacés de 3 cm. Au pinceau : huile (2 c. à s.), 9 g de sel, poivre, rondelles de citron dessus, moitié des herbes.||2',
    'enfourner|truite|18|P|Cuire au four|200 °C, 15–18 min. Chair opaque qui se sépare en feuillets, sonde 63 °C au plus épais.|63',
    'couper|legumes|6||Tailler les légumes|Légumes de saison au même calibre : bâtonnets de 5 mm ou fleurettes de 3 cm.',
    'bouillir|légumes|8|P|Légumes vapeur|Panier sur une eau à gros bouillons, couvercle, 5–8 min selon le légume : vert vif, légère résistance au couteau. Bain glacé 2 min, égoutter, sécher.',
    'refrigerer|truite|30|P|Refroidir|Truite et légumes étalés, 10 °C à cœur en moins de 2 h.',
    'dresser|truite + légumes|2|A|Dresser|Tare. 100 g de légumes, un filet de truite (150 g) avec sa rondelle de citron, reste des herbes et un filet d’huile dessus. Opercule sans buée, étiquette.'] },

{ nom: 'Truite vapeur, écrasé de patate douce', code: 'PM', fichier: 'Truite vapeur et son écrasé de patate douce PM',
  desc: 'Filet de truite vapeur, écrasé de patate douce à l’huile d’olive et ciboulette, légumes vapeur.',
  ing: ['truite|900|6 filets', 'patate douce|600|600 g', 'huile olive|42|3 c. à s.', 'ail|10|2 gousses', 'ciboulette|10|1/4 tasse', 'legumes|600|vapeur, pour accompagner', 'sel|0|q.s.'],
  etapes: [
    'couper|patates douces, ail, ciboulette|8||Tailler|Patates douces pelées, cubes de 3 cm, sous l’eau froide. Ail dégermé, émincé. Ciboulette aux ciseaux.',
    'bouillir|patates douces|18|P|Cuire les patates douces|Départ eau FROIDE salée (10 g/l), 3 cm au-dessus. Ébullition puis bouillon modéré, 15–20 min : la pointe du couteau entre sans résistance. Égoutter, 1 min dans la casserole sur le feu éteint pour sécher.',
    'mixer|patates douces|5||Écraser|CHAUD, au presse-purée ou à la fourchette — jamais au mixeur, ça colle. Huile (1 c. à s.), ail, 6 g de sel, poivre. Détendre avec 2–3 c. à s. d’eau de cuisson chaude jusqu’à souple. Ciboulette en fin.',
    'assaisonner|truite|2||Saler la truite|Filets séchés, 9 g de sel, poivre.',
    'bouillir|truite|9|P|Truite vapeur|Panier vapeur sur une eau qui bout franchement, couvercle, filets sans qu’ils se touchent, 8–10 min. Chair opaque en feuillets, sonde 63 °C.|63',
    'couper|legumes|6||Tailler les légumes|Légumes de saison au même calibre : bâtonnets de 5 mm ou fleurettes de 3 cm.',
    'bouillir|légumes|8|P|Légumes vapeur|Même panier, 5–8 min : vert vif, légère résistance. Bain glacé, égoutter, sécher.',
    'refrigerer|truite|30|P|Refroidir|Truite, écrasé et légumes étalés, 10 °C à cœur en moins de 2 h.',
    'dresser|truite + écrasé + légumes|2|A|Dresser|Tare. 100 g d’écrasé, 100 g de légumes, un filet de truite (150 g). Opercule sans buée, étiquette.'] }
];
