/* Les 38 fiches techniques de Natty (dossier « fiche rectte natty », septembre 2026),
   transcrites depuis les .docx. Toutes sont écrites POUR 6 PORTIONS (la dernière
   fiche le dit : « permettant de réaliser 6 portions » — et les 6 filets, 6
   tortillas, 6 cuisses le confirment).

   FORMAT — volontairement compact, pour qu'on puisse relire 38 fiches d'un coup :
     ing  : "nom | grammes pour 6 portions | quantité telle qu'écrite sur la fiche"
            ⚠️ les féculents (riz, quinoa, lentilles, boulgour, millet) sont en
            poids CUIT dans `g`, comme l'attend la table de core.js — le `qte`
            affiché dit le cru (voir scripts/injecter-recettes.mjs).
            Une conserve « 400 g » égouttée pèse ~250 g ; une tasse fait 240 ml.
     etape: "geste | aliment | durée min | drapeaux | titre | description"
            geste ∈ les 16 gestes d'assets/recette.js (couper, saisir, bouillir,
            mijoter, enfourner, melanger, fouetter, mixer, assaisonner, huiler,
            rincer, peser, refrigerer, reposer, attendre, dresser) — c'est ce
            que l'onglet Production trie ; aliment = ce sur quoi porte le geste.
            drapeaux : P = passif (four, mijotage, marinade : le cuisinier est
            libre), A = assemblage (par portion, pas en masse). Une durée non
            écrite sur la fiche est ESTIMÉE — la fiche ne donne que les temps de
            cuisson, jamais ceux de découpe.
   code : PS = prise de masse (le titre du Bourguignon PS le dit), PP = perte de
          poids, PM = ?, VG = végétarien, SG = sans gluten. 🔄 PM à confirmer par Pablo.
   « Steak de thon salsa mango PS (2).docx » est un doublon du Risotto de boulgour
   SG (même contenu) : ignoré. */
export const PORTIONS = 6;

export const FICHES = [
{ nom: 'Boulettes de dinde, salade de chou', code: 'SG', fichier: 'Boulette de dinde SG',
  desc: 'Boulettes de dinde dorées à la poêle, salade de chou râpé au yaourt grec et à l’ail.',
  ing: ['dinde hachée|1200|1,2 kg', 'chapelure sans gluten|60|1/2 tasse', 'lait|60|1/4 tasse', 'oeuf|55|1',
    'oignon|150|1', 'ail|10|2 gousses', 'persil|5|1 c. à s.', 'huile olive|42|3 c. à s.', 'chou|600|600 g râpé',
    'yaourt grec|150|150 g', 'ail|15|3 c. de pulpe', 'sel|0|q.s.'],
  etapes: ['couper|oignon, ail, persil|8||Hacher|Hacher l’oignon, l’ail et le persil.',
    'melanger|dinde hachée|10||Façonner les boulettes|Mélanger dinde, chapelure, lait, œuf, oignon, ail, persil, sel et poivre. Former des boulettes.',
    'saisir|boulettes de dinde|15||Cuire les boulettes|Poêle chaude à l’huile d’olive, dorer sur toutes les faces, environ 15 min.',
    'melanger|chou râpé|6||Salade de chou|Mélanger le chou, le yaourt grec et la pulpe d’ail ; assaisonner.',
    'dresser|boulettes + salade de chou|2|A|Dresser|Boulettes et salade de chou dans la boîte.'] },

{ nom: 'Bœuf bourguignon (prise de masse)', code: 'PS', fichier: 'Bourguignon PS',
  desc: 'Bœuf mijoté au vin rouge, carottes, champignons, servi avec des pommes de terre.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|720|6', 'oignon|450|3', 'vin rouge|0|1,5 L (alcool évaporé : non compté)',
    'bouillon de boeuf|750|750 ml', 'champignons|300|300 g', 'farine|30|3 c. à s.', 'huile olive|42|3 c. à s.',
    'thym|0|3 branches', 'laurier|0|3 feuilles', 'pomme de terre|1500|1,5 kg', 'sel|0|q.s.'],
  etapes: ['couper|boeuf, carottes, oignons, champignons|20||Tailler|Bœuf en cubes, carottes en rondelles, oignons émincés, champignons en quartiers.',
    'saisir|boeuf|12||Dorer le bœuf|Cocotte, huile chaude : dorer les cubes de bœuf. Réserver.',
    'saisir|oignons, carottes|8||Revenir les légumes|Dans la même cocotte, faire revenir oignons et carottes.',
    'melanger|boeuf, farine|3||Singer|Remettre la viande, ajouter la farine, bien mélanger.',
    'assaisonner|vin, bouillon, thym, laurier|3||Mouiller|Ajouter vin rouge, bouillon, thym, laurier. Saler, poivrer.',
    'mijoter|bourguignon|150|P|Mijoter 2 h 30|Feu doux, couvert. Ajouter les champignons 30 min avant la fin.',
    'bouillir|pommes de terre|25||Cuire les pommes de terre|À l’eau bouillante salée.',
    'dresser|bourguignon + pommes de terre|2|A|Dresser|Bœuf, sauce et pommes de terre dans la boîte.'] },

{ nom: 'Bourguignon by Natty (sans gluten)', code: 'SG', fichier: 'Bourguignon by natty SG',
  desc: 'Le bourguignon, lié à la farine de riz : sans gluten.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|720|6', 'oignon|450|3', 'vin rouge|0|1,5 L (alcool évaporé : non compté)',
    'bouillon de boeuf|750|750 ml', 'champignons|300|300 g', 'farine de riz|30|3 c. à s.', 'huile olive|42|3 c. à s.',
    'thym|0|3 branches', 'laurier|0|3 feuilles', 'pomme de terre|1500|1,5 kg', 'sel|0|q.s.'],
  etapes: ['couper|boeuf, carottes, oignons, champignons|20||Tailler|Bœuf en cubes, carottes en rondelles, oignons émincés, champignons en quartiers.',
    'saisir|boeuf|12||Dorer le bœuf|Cocotte, huile chaude : dorer les cubes. Réserver.',
    'saisir|oignons, carottes|8||Revenir les légumes|Dans la même cocotte.',
    'melanger|boeuf, farine de riz|3||Lier|Remettre la viande, farine de riz, mélanger.',
    'assaisonner|vin, bouillon, thym, laurier|3||Mouiller|Vin, bouillon, thym, laurier. Assaisonner.',
    'mijoter|bourguignon|150|P|Mijoter 2 h 30|Champignons 30 min avant la fin.',
    'bouillir|pommes de terre|25||Cuire les pommes de terre|À l’eau bouillante salée.',
    'dresser|bourguignon + pommes de terre|2|A|Dresser|Dans la boîte.'] },

{ nom: 'Burger de lentilles', code: 'PS', fichier: 'Burger de lentilles PS',
  desc: 'Galettes de lentilles et chou-fleur, pain complet, avocat, tomate, salade.',
  ing: ['lentilles|400|2 tasses cuites', 'chou-fleur|200|1 tasse cuit', 'flocons avoine|45|1/2 tasse', 'oignon|150|1',
    'ail|10|2 gousses', 'cumin|6|1 c. à s.', 'sauce soja|15|1 c. à s.', 'huile olive|28|2 c. à s.', 'pain complet|360|6 pains',
    'avocat|170|1', 'tomate|240|2', 'salade|90|quelques feuilles', 'sel|0|q.s.'],
  etapes: ['couper|oignon, ail|5||Hacher|Oignon haché fin, ail émincé.',
    'saisir|oignon, ail|5||Revenir|Poêle, un peu d’huile, jusqu’à translucide.',
    'mixer|lentilles, chou-fleur, flocons|8||Écraser la farce|Lentilles, chou-fleur, flocons, cumin, sauce soja, sel, poivre : écraser à la fourchette.',
    'melanger|farce de lentilles|8||Former les galettes|6 galettes.',
    'saisir|galettes de lentilles|14||Cuire les galettes|5 à 7 min de chaque côté, poêle antiadhésive.',
    'couper|avocat, tomate|5|A|Tailler la garniture|Avocat et tomate en tranches.',
    'dresser|burger|3|A|Monter le burger|Pain, galette, avocat, tomate, salade.'] },

{ nom: 'Burritos végétariens au quinoa', code: 'SG', fichier: 'Buritos vegetarien au quinoa SG',
  desc: 'Tortillas de maïs garnies de quinoa, haricots noirs, avocat, tomate, maïs et coriandre.',
  ing: ['quinoa|510|1 tasse (cru) → cuit', 'haricots noirs|250|1 boîte égouttée', 'avocat|170|1', 'tomate|120|1',
    'oignon rouge|75|1/2', 'poivron rouge|150|1', 'mais|80|1/2 tasse', 'coriandre|10|1/4 tasse', 'tortilla mais|360|6',
    'jus de citron|40|1 citron', 'sel|0|q.s.'],
  etapes: ['bouillir|quinoa|15|P|Cuire le quinoa|Dans 2 tasses d’eau, à couvert.',
    'couper|avocat, tomate, oignon rouge, poivron, coriandre|12||Tailler|Avocat, tomate, poivron en dés ; oignon et coriandre hachés.',
    'melanger|haricots noirs, légumes|4||Mélanger la garniture|Haricots, avocat, tomate, oignon, poivron, maïs, coriandre.',
    'assaisonner|garniture au quinoa|3||Assaisonner|Ajouter le quinoa cuit, jus de citron, sel, poivre.',
    'saisir|tortillas|4|A|Chauffer les tortillas|À sec, à la poêle.',
    'dresser|burrito|3|A|Garnir et rouler|Une tortilla, la garniture, rouler.'] },

{ nom: 'Bœuf braisé aux légumes', code: 'PM', fichier: 'Bœuf braisé PM',
  desc: 'Cubes de bœuf braisés au bouillon avec carottes, céleri et oignon.',
  ing: ['boeuf|1500|1,5 kg gîte ou paleron', 'carotte|480|4', 'celeri|100|2 branches', 'oignon|150|1',
    'bouillon de boeuf|750|750 ml', 'huile olive|42|3 c. à s.', 'laurier|0|2 feuilles', 'thym|0|3 branches', 'sel|0|q.s.'],
  etapes: ['couper|boeuf, carottes, céleri, oignon|15||Tailler|Bœuf en cubes, carottes en rondelles, céleri en dés, oignon haché.',
    'saisir|boeuf|12||Saisir le bœuf|Cocotte, huile chaude, dorer sur toutes les faces.',
    'saisir|oignon, carottes, céleri|6||Revenir les légumes|Quelques minutes.',
    'assaisonner|bouillon, laurier, thym|2||Mouiller|Bouillon, laurier, thym, sel, poivre.',
    'mijoter|boeuf braisé|150|P|Braiser 2 h 30|Couvert, feu doux, jusqu’à tendreté.',
    'dresser|boeuf braisé|2|A|Dresser|Dans la boîte.'] },

{ nom: 'Cabillaud et pois chiches', code: 'PM', fichier: 'Cabillaud et pois chiches PM',
  desc: 'Filet de cabillaud poêlé, sauté de pois chiches et épinards à l’ail, jus de citron.',
  ing: ['cabillaud|900|6 filets', 'pois chiches|500|2 boîtes égouttées', 'epinards|300|300 g frais', 'huile olive|42|3 c. à s.',
    'jus de citron|45|3 c. à s.', 'ail|10|2 gousses', 'sel|0|q.s.'],
  etapes: ['couper|ail|2||Émincer l’ail|',
    'saisir|cabillaud|10||Cuire le cabillaud|2 c. à s. d’huile, 4-5 min de chaque côté.',
    'saisir|pois chiches, épinards|5||Sauter pois chiches et épinards|Reste d’huile, ail, pois chiches, épinards jusqu’à ce qu’ils tombent (3-4 min).',
    'dresser|cabillaud + pois chiches|2|A|Dresser|Cabillaud sur les pois chiches, filet de citron.'] },

{ nom: 'Chili con carne', code: 'SG', fichier: 'Chili con carne SG',
  desc: 'Bœuf haché mijoté aux haricots rouges et noirs, tomates, chili et cumin, avec du riz.',
  ing: ['boeuf hache|1500|1,5 kg', 'haricots rouges|250|1 boîte égouttée', 'haricots noirs|250|1 boîte égouttée',
    'tomates concassees|400|1 boîte', 'oignon|150|1', 'ail|20|4 gousses', 'chili en poudre|12|2 c. à s.', 'cumin|6|1 c. à s.',
    'huile olive|42|3 c. à s.', 'riz|1200|~460 g cru → cuit', 'sel|0|q.s.'],
  etapes: ['couper|oignon, ail|5||Hacher|Oignon haché fin, ail émincé.',
    'saisir|oignon, ail|5||Revenir|Casserole, huile, jusqu’à translucide.',
    'saisir|boeuf haché|10||Dorer le bœuf|Bien doré.',
    'melanger|chili, cumin, tomates, haricots|3||Incorporer|Épices, tomates concassées, haricots.',
    'mijoter|chili|30|P|Mijoter 30 min|Feu doux ; saler, poivrer.',
    'bouillir|riz|18||Cuire le riz|À l’eau.',
    'dresser|chili + riz|2|A|Dresser|Riz au fond, chili dessus.'] },

{ nom: 'Chili sin carne, haricots noirs et quinoa', code: 'PS', fichier: 'Chili sin carne PS',
  desc: 'Chili végétarien : haricots noirs, tomates, poivron, quinoa, avocat en condiment.',
  ing: ['quinoa|510|1 tasse (cru) → cuit', 'haricots noirs|250|1 boîte égouttée', 'tomates concassees|400|1 boîte', 'poivron rouge|150|1',
    'oignon|150|1', 'ail|10|2 gousses', 'chili en poudre|12|2 c. à s.', 'cumin|6|1 c. à s.', 'huile olive|14|1 c. à s.', 'avocat|170|1', 'sel|0|q.s.'],
  etapes: ['bouillir|quinoa|15|P|Cuire le quinoa|Dans 2 tasses d’eau.',
    'couper|oignon, ail, poivron|8||Tailler|Oignon haché, ail émincé, poivron en dés.',
    'saisir|oignon, ail, poivron|6||Revenir|Casserole, huile, jusqu’à tendreté.',
    'melanger|tomates, haricots noirs, épices|2||Ajouter|Tomates, haricots, chili, cumin.',
    'mijoter|chili sin carne|18|P|Mijoter 15-20 min|',
    'assaisonner|chili + quinoa|3||Incorporer le quinoa|Quinoa cuit, sel, poivre.',
    'couper|avocat|3|A|Avocat en dés|',
    'dresser|chili sin carne|2|A|Dresser|Chili, dés d’avocat dessus.'] },

{ nom: 'Courgettes farcies au quinoa', code: 'SG', fichier: 'Courgettes farcies SG',
  desc: 'Barques de courgette farcies au quinoa, poivron et tomate, cuites sur un lit de sauce tomate.',
  ing: ['courgette|1200|6', 'quinoa|540|1,5 tasse (cuit)', 'poivron rouge|150|1', 'oignon|150|1', 'tomate|240|2',
    'sauce tomate|400|1 boîte', 'huile olive|28|2 c. à s.', 'basilic|3|q.s.', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer le four|190 °C.',
    'couper|courgettes|12||Creuser les courgettes|Couper en deux dans la longueur, retirer la pulpe à la cuillère. Garder la pulpe.',
    'couper|poivron, oignon, tomates|8||Tailler|Poivron et tomates en dés, oignon haché.',
    'saisir|oignon, poivron, pulpe, tomates, quinoa|10||Farce|Revenir oignon et poivron, ajouter pulpe, tomates, quinoa. Sel, poivre, herbes.',
    'dresser|courgettes, farce|8||Farcir|Remplir chaque demi-courgette ; sauce tomate au fond du plat, courgettes dessus.',
    'enfourner|courgettes farcies|33|P|Cuire au four|Couvert d’aluminium, 30-35 min à 190 °C.',
    'dresser|courgettes farcies|2|A|Dresser|Deux demi-courgettes par boîte, un peu de sauce.'] },

{ nom: 'Curry de légumes', code: 'VG', fichier: 'Curry de legumes végétarien VG',
  desc: 'Carottes, brocoli et pois chiches au lait de coco et pâte de curry, riz basmati.',
  ing: ['carotte|260|2 tasses en dés', 'brocoli|180|2 tasses de bouquets', 'pois chiches|250|1 boîte égouttée', 'lait de coco|400|1 boîte',
    'oignon|150|1', 'ail|10|2 gousses', 'pate de curry|30|2 c. à s.', 'huile olive|28|2 c. à s.', 'riz|1400|3 tasses (cru) → cuit', 'sel|0|q.s.'],
  etapes: ['couper|oignon, ail, carottes, brocoli|12||Tailler|Oignon haché, ail émincé, carottes en dés, brocoli en bouquets.',
    'saisir|oignon, ail|5||Revenir|Casserole, huile.',
    'saisir|carottes, brocoli|5||Revenir les légumes|5 min.',
    'melanger|pâte de curry|1||Pâte de curry|Bien enrober.',
    'mijoter|curry de légumes|18|P|Mijoter 15-20 min|Pois chiches, lait de coco ; jusqu’à tendreté. Sel, poivre.',
    'bouillir|riz basmati|15||Cuire le riz|',
    'dresser|curry + riz|2|A|Dresser|Riz, curry dessus.'] },

{ nom: 'Curry de poulet rôti, riz complet', code: 'PS', fichier: 'Curry de poulet  PS',
  desc: 'Poulet rôti en morceaux dans un curry au lait de coco, haricots verts et carottes, riz complet.',
  ing: ['poulet|900|900 g rôti désossé', 'oignon|300|2', 'ail|20|4 gousses', 'pate de curry|30|2 c. à s.', 'lait de coco|800|2 boîtes',
    'haricots verts|300|300 g', 'carotte|300|300 g', 'riz complet|1560|600 g (cru) → cuit', 'huile olive|56|4 c. à s.', 'sel|0|q.s.'],
  etapes: ['couper|oignons, ail, carottes, poulet|15||Tailler|Oignons hachés fin, ail émincé, carottes en rondelles, poulet en morceaux.',
    'saisir|oignons, ail|5||Revenir|Poêle, huile, jusqu’à translucide.',
    'melanger|pâte de curry|1||Pâte de curry|Mélanger.',
    'mijoter|lait de coco|5|P|Mijoter la sauce|5 min.',
    'mijoter|poulet, légumes|10|P|Cuire poulet et légumes|Environ 10 min, légumes tendres.',
    'bouillir|riz complet|35||Cuire le riz complet|',
    'dresser|curry + riz|2|A|Dresser|Lit de riz, curry dessus.'] },

{ nom: 'Dinde à la vapeur, légumes', code: 'PP', fichier: 'Dinde vapeur PP',
  desc: 'Poitrine de dinde et légumes cuits à la vapeur, sauce soja en option.',
  ing: ['dinde|1500|1,5 kg de poitrines', 'carotte|260|', 'haricots verts|260|', 'brocoli|260|6 tasses de légumes au total',
    'sauce soja|45|3 c. à s.', 'thym|0|q.s.', 'sel|0|q.s.'],
  etapes: ['assaisonner|dinde|4||Assaisonner la dinde|Sel, poivre, herbes.',
    'bouillir|dinde|28|P|Cuire la dinde à la vapeur|25-30 min, cœur à 75 °C.',
    'couper|carottes, haricots, brocoli|8||Tailler les légumes|',
    'bouillir|légumes|6|P|Légumes à la vapeur|5-7 min.',
    'couper|dinde|4|A|Trancher la dinde|',
    'dresser|dinde + légumes|2|A|Dresser|Sauce soja si désiré.'] },

{ nom: 'Filet de dinde grillé, citron confit', code: 'PM', fichier: 'Filet de dinde grillé au citrons confit PM',
  desc: 'Dinde marinée au citron, grillée, riz basmati, légumes vapeur, sauce vierge au citron confit.',
  ing: ['dinde|1080|6 filets', 'riz basmati|1560|600 g (cru) → cuit', 'brocoli|200|', 'carotte|200|', 'haricots verts|200|600 g de légumes au total',
    'huile olive|42|3 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: ['fouetter|huile, citron|3||Marinade|Huile, jus de citron, sel, poivre.',
    'refrigerer|dinde|30|P|Mariner 30 min|Filets dans la marinade.',
    'bouillir|riz basmati|15||Cuire le riz|',
    'saisir|dinde|14||Griller la dinde|Poêle moyen-vif, 6-7 min par face.',
    'bouillir|légumes|7|P|Légumes vapeur|Jusqu’à tendreté.',
    'melanger|sauce vierge|5||Sauce vierge|Parures de légumes, citron confit.',
    'dresser|dinde + riz + légumes|2|A|Dresser|'] },

{ nom: 'Merlu en papillote', code: 'PP', fichier: 'Merlu en papillote PP',
  desc: 'Filet de merlu, tomate, citron et thym en papillote au four.',
  ing: ['merlu|900|6 filets', 'tomate|720|6', 'citron|100|1', 'thym|0|6 branches', 'huile olive|84|6 c. à s.', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer|200 °C.',
    'couper|tomates, citron|6||Rondelles|Tomates et citron en rondelles.',
    'dresser|merlu, tomates, citron, thym|10||Monter les papillotes|Un filet par feuille, rondelles dessus, sel, poivre, thym, huile ; fermer hermétiquement.',
    'enfourner|papillotes de merlu|23|P|Cuire au four|20-25 min à 200 °C.',
    'dresser|papillote|2|A|Dresser|Ouvrir avec précaution, en boîte.'] },

{ nom: 'Merlu poché, brocoli, kale et mangue', code: 'PP', fichier: 'Merlu poché PP',
  desc: 'Merlu poché au vin blanc et bouquet garni, brocoli, chou kale, dés de mangue.',
  ing: ['merlu|900|6 filets', 'vin blanc|120|1/2 tasse', 'thym|0|bouquet garni', 'brocoli|300|300 g', 'mangue|250|1', 'chou kale|300|300 g'],
  etapes: ['couper|brocoli, kale, mangue|8||Tailler|Brocoli en bouquets, kale haché, mangue en dés.',
    'bouillir|court-bouillon|8||Porter à ébullition|Eau, vin, bouquet garni.',
    'bouillir|merlu|9|P|Pocher le merlu|8-10 min.',
    'bouillir|brocoli, kale|6||Cuire les légumes|Brocoli 3-4 min, kale 2 min de plus. Égoutter.',
    'dresser|merlu + légumes + mangue|2|A|Dresser|'] },

{ nom: 'Natty wrap', code: 'PP', fichier: 'Natty wrap PP',
  desc: 'Tortilla complète, poulet grillé, poivron, carotte, concombre, sauce yaourt-citron.',
  ing: ['tortilla|360|6 tortillas', 'poulet|600|600 g grillé', 'poivron|150|1', 'carotte|120|1', 'concombre|300|1',
    'yaourt nature|120|1/2 tasse', 'jus de citron|30|2 c. à s.', 'menthe|5|q.s.', 'sel|0|q.s.'],
  etapes: ['fouetter|yaourt, citron|4||Sauce yaourt|Yaourt, jus de citron, sel, poivre, herbes hachées.',
    'couper|poivron, carotte, concombre, poulet|12||Tailler|Poivron en lanières, carotte en julienne, concombre en bâtonnets, poulet en lanières.',
    'dresser|tortilla, poulet, légumes|3|A|Garnir|Poulet, poivron, carotte, concombre sur la tortilla.',
    'dresser|sauce yaourt|1|A|Sauce|Quelques cuillères sur les légumes.',
    'dresser|wrap|2|A|Rouler et couper|Rouler fermement, couper en deux.'] },

{ nom: 'Poulet à la moutarde, riz complet, légumes rôtis', code: 'PS', fichier: 'Poulet a la moutarde PS',
  desc: 'Cuisses de poulet badigeonnées de moutarde, rôties, riz complet, carottes et courgettes rôties.',
  ing: ['cuisse de poulet|1500|6 cuisses', 'moutarde|90|6 c. à s.', 'huile olive|56|4 c. à s.', 'thym|1|1 c. à c.',
    'riz complet|1560|600 g (cru) → cuit', 'carotte|300|', 'courgette|300|600 g de légumes au total', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer|200 °C.',
    'assaisonner|poulet, moutarde|6||Badigeonner|Moutarde, sel, poivre, thym sur chaque cuisse.',
    'saisir|poulet|8||Dorer le poulet|Poêle, huile, des deux côtés.',
    'couper|carottes, courgettes|8||Tailler les légumes|En morceaux.',
    'enfourner|poulet|33|P|Rôtir le poulet|30-35 min ; légumes à côté les 15 dernières minutes.',
    'bouillir|riz complet|35||Cuire le riz complet|',
    'dresser|poulet + riz + légumes|2|A|Dresser|'] },

{ nom: 'Poulet aux épinards, riz complet', code: 'PM', fichier: 'Poulet aux epinards PM',
  desc: 'Poitrine de poulet dorée, épinards à l’ail et muscade, riz complet.',
  ing: ['poulet|1080|6 poitrines', 'epinards|500|500 g frais', 'ail|20|4 gousses', 'huile olive|42|3 c. à s.', 'muscade|2|1 c. à c.',
    'riz complet|1560|600 g (cru) → cuit', 'sel|0|q.s.'],
  etapes: ['bouillir|riz complet|35||Cuire le riz complet|',
    'couper|ail|2||Émincer l’ail|',
    'saisir|poulet|14||Dorer le poulet|2 c. à s. d’huile, 6-7 min par face. Réserver.',
    'saisir|épinards, ail|5||Tomber les épinards|Même poêle, reste d’huile, ail ; muscade, sel, poivre.',
    'dresser|poulet + épinards + riz|2|A|Dresser|Poulet sur lit d’épinards, riz à côté.'] },

{ nom: 'Poulet rôti aux légumes', code: 'SG', fichier: 'Poulet rôti aux légumes SG',
  desc: 'Cuisses de poulet rôties sur un lit de carottes, pommes de terre et courgettes.',
  ing: ['cuisse de poulet|1500|6 cuisses', 'carotte|500|', 'pomme de terre|500|', 'courgette|500|1,5 kg de légumes au total',
    'huile olive|56|4 c. à s.', 'herbes de provence|6|2 c. à s.', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer|200 °C.',
    'assaisonner|poulet|4||Assaisonner le poulet|Sel, poivre, herbes.',
    'couper|carottes, pommes de terre, courgettes|15||Tailler les légumes|En morceaux, dans le plat, huile, assaisonner.',
    'enfourner|poulet + légumes|45|P|Rôtir 45 min|Poulet sur les légumes, jusqu’à doré.',
    'dresser|poulet rôti + légumes|2|A|Dresser|'] },

{ nom: 'Quinoa bowl, légumes grillés, sauce tahini', code: 'VG', fichier: 'Quinoa bowl VG',
  desc: 'Quinoa, courgettes, poivrons et aubergine rôtis, sauce tahini-citron.',
  ing: ['quinoa|765|1,5 tasse (cru) → cuit', 'courgette|400|2', 'poivron|300|2', 'aubergine|300|1', 'huile olive|56|1/4 tasse',
    'tahini|60|1/4 tasse', 'jus de citron|30|2 c. à s.', 'ail|5|1 gousse', 'sel|0|q.s.'],
  etapes: ['bouillir|quinoa|15|P|Cuire le quinoa|Eau bouillante, feu doux, couvert 15 min ; laisser reposer.',
    'enfourner|four|10|P|Préchauffer|200 °C.',
    'couper|courgettes, poivrons, aubergine|12||Tailler|Rondelles, lanières, cubes.',
    'huiler|légumes|3||Huiler et assaisonner|Sur la plaque, huile, sel, poivre.',
    'enfourner|légumes|23|P|Rôtir 20-25 min|',
    'fouetter|tahini, citron, ail|4||Sauce tahini|Tahini, citron, ail, sel, eau jusqu’à lisse.',
    'dresser|quinoa + légumes + tahini|2|A|Monter le bowl|Quinoa, légumes, sauce.'] },

{ nom: 'Risotto aux champignons', code: 'PS', fichier: 'Risotto aux champignons PS',
  desc: 'Riz arborio crémeux aux champignons et parmesan, persil.',
  ing: ['riz arborio|760|1,5 tasse (cru) → cuit', 'bouillon de legumes|1440|6 tasses', 'champignons|400|400 g', 'oignon|150|1',
    'huile olive|56|4 c. à s.', 'parmesan|50|1/2 tasse', 'beurre|30|2 c. à s.', 'persil|5|q.s.', 'sel|0|q.s.'],
  etapes: ['couper|champignons, oignon|8||Tailler|Champignons tranchés, oignon haché fin.',
    'bouillir|bouillon|8|P|Chauffer le bouillon|Feu doux.',
    'saisir|oignon, champignons|7||Revenir|Poêle, huile, feu moyen.',
    'melanger|riz arborio|2||Nacrer le riz|2 min pour enrober.',
    'mijoter|risotto|20||Mouiller louche par louche|Remuer jusqu’à absorption, ~20 min.',
    'melanger|parmesan, beurre|2||Mantecare|Parmesan, beurre, sel, poivre.',
    'dresser|risotto|2|A|Dresser|Persil frais.'] },

{ nom: 'Risotto de boulgour, petits pois et carottes', code: 'SG', fichier: 'Risotto de boulgour SG',
  desc: 'Boulgour cuit façon risotto au bouillon, petits pois, carottes, parmesan.',
  ing: ['boulgour|750|1,5 tasse (cru) → cuit', 'bouillon de legumes|960|4 tasses', 'petits pois|150|1 tasse', 'carotte|240|2', 'oignon|150|1',
    'huile olive|56|4 c. à s.', 'parmesan|50|1/2 tasse', 'sel|0|q.s.'],
  etapes: ['couper|carottes, oignon|6||Tailler|Carottes en dés, oignon haché.',
    'bouillir|bouillon|8|P|Chauffer le bouillon|Feu doux.',
    'saisir|oignon|5||Revenir|Poêle, huile, jusqu’à translucide.',
    'mijoter|boulgour|12||Mouiller louche par louche|Boulgour, bouillon chaud, remuer.',
    'mijoter|petits pois, carottes|8||Finir la cuisson|Ajouter petits pois et carottes, jusqu’à tendreté.',
    'melanger|parmesan|2||Parmesan|Sel, poivre.',
    'dresser|risotto de boulgour|2|A|Dresser|'] },

{ nom: 'Salade de lentilles', code: 'VG', fichier: 'Salade de lentille VG',
  desc: 'Lentilles vertes, concombre, poivron, carotte, oignon rouge, pignons, vinaigrette moutarde-cidre.',
  ing: ['lentilles|400|2 tasses cuites', 'concombre|300|1', 'poivron rouge|150|1', 'carotte|120|1', 'oignon rouge|75|1/2',
    'pignons de pin|45|1/3 tasse', 'huile olive|84|6 c. à s.', 'vinaigre de cidre|30|2 c. à s.', 'moutarde|5|1 c. à c.', 'persil|10|1/4 tasse', 'sel|0|q.s.'],
  etapes: ['couper|concombre, poivron, carotte, oignon rouge, persil|12||Tailler|Concombre et poivron en dés, carotte râpée, oignon haché fin, persil haché.',
    'saisir|pignons|3||Griller les pignons|À sec, légèrement.',
    'fouetter|huile, vinaigre, moutarde|3||Vinaigrette|Sel, poivre.',
    'melanger|lentilles, légumes|4||Assembler|Lentilles, légumes, pignons.',
    'dresser|salade de lentilles|2|A|Dresser|Vinaigrette, persil dessus.'] },

{ nom: 'Salade de poulet grillé', code: 'PP', fichier: 'Salade de poulet  grillé 2 PP',
  desc: 'Poitrine de poulet grillée sur laitue, tomates cerises et concombre, vinaigrette balsamique.',
  ing: ['poulet|1080|6 poitrines', 'laitue|300|300 g', 'tomates cerises|300|300 g', 'concombre|300|1',
    'huile olive|84|6 c. à s.', 'vinaigre balsamique|45|3 c. à s.', 'sel|0|q.s.'],
  etapes: ['assaisonner|poulet|3||Assaisonner|Sel, poivre.',
    'saisir|poulet|14||Griller le poulet|6-7 min par face, poêle ou barbecue.',
    'reposer|poulet|8|P|Laisser tiédir|Puis trancher.',
    'couper|tomates cerises, concombre, poulet|8||Tailler|Tomates en deux, concombre en rondelles, poulet en tranches.',
    'fouetter|huile, balsamique|2||Vinaigrette|Sel, poivre.',
    'dresser|salade + poulet|2|A|Dresser|Salade, poulet, vinaigrette.'] },

{ nom: 'Salade de poulet grillé, vinaigrette avocat-citron', code: 'PS', fichier: 'Salade de poulet grillé avocat citron PS',
  desc: 'Poulet grillé, laitue, concombre, tomates cerises et une vinaigrette crémeuse à l’avocat.',
  ing: ['poulet|540|3 poitrines', 'laitue|300|300 g', 'concombre|300|1', 'tomates cerises|300|300 g', 'avocat|340|2',
    'huile olive|56|4 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: ['saisir|poulet|14||Griller le poulet|6-7 min par face.',
    'reposer|poulet|8|P|Laisser tiédir|Puis trancher.',
    'couper|concombre, tomates cerises, poulet|8||Tailler|Concombre en rondelles, tomates en deux, poulet en tranches.',
    'mixer|avocats|4||Vinaigrette avocat|Écraser les avocats, huile, citron, sel, poivre.',
    'dresser|salade + poulet + vinaigrette|2|A|Dresser|'] },

{ nom: 'Salade de quinoa', code: 'VG', fichier: 'Salade de quinoa VG',
  desc: 'Quinoa, concombre, tomates, poivron, oignon rouge, avocat, coriandre, citron.',
  ing: ['quinoa|765|1,5 tasse (cru) → cuit', 'concombre|300|1', 'tomate|240|2', 'poivron rouge|150|1', 'oignon rouge|75|1/2',
    'avocat|340|2', 'coriandre|10|1/4 tasse', 'huile olive|84|6 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: ['bouillir|quinoa|15|P|Cuire le quinoa|Couvert, feu doux, 15 min.',
    'reposer|quinoa|5|P|Reposer 5 min|Puis égrener à la fourchette.',
    'couper|concombre, tomates, poivron, oignon rouge, avocats, coriandre|14||Tailler|Tout en dés, oignon et coriandre hachés.',
    'melanger|quinoa, légumes|4||Assembler|Quinoa égrené, légumes, avocat.',
    'fouetter|huile, citron|2||Vinaigrette|Sel, poivre.',
    'dresser|salade de quinoa|2|A|Dresser|Vinaigrette, mélanger délicatement.'] },

{ nom: 'Salade de millet aux agrumes', code: 'SG', fichier: 'Salade millet aux agrumes SG',
  desc: 'Millet, orange, pamplemousse, amandes effilées, raisins secs, vinaigrette au cidre.',
  ing: ['millet|900|1,5 tasse (cru) → cuit', 'orange|360|2', 'pamplemousse|300|1', 'amandes effilees|30|1/4 tasse', 'raisins secs|40|1/4 tasse',
    'huile olive|56|1/4 tasse', 'vinaigre de cidre|45|3 c. à s.', 'sel|0|q.s.'],
  etapes: ['bouillir|millet|18|P|Cuire le millet|Couvert, feu doux, 15-20 min.',
    'reposer|millet|5|P|Reposer 5 min|Égrener.',
    'couper|oranges, pamplemousse|8||Peler et tailler les agrumes|En dés.',
    'saisir|amandes|3||Griller les amandes|À sec.',
    'fouetter|huile, vinaigre|2||Vinaigrette|Sel, poivre.',
    'melanger|millet, agrumes, amandes, raisins|4||Assembler|',
    'dresser|salade de millet|2|A|Dresser|Vinaigrette.'] },

{ nom: 'Saumon aux amandes, quinoa, asperges', code: 'PS', fichier: 'Saumon grillé aux amandes PS',
  desc: 'Filet de saumon en croûte d’amandes au citron, quinoa et asperges vapeur.',
  ing: ['saumon|900|6 filets', 'amandes effilees|150|1,5 tasse', 'huile olive|56|4 c. à s.', 'citron|60|1 (jus et zeste)',
    'quinoa|1530|3 tasses (cru) → cuit', 'asperges|450|1,5 botte', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer|180 °C.',
    'melanger|amandes, citron|3||Croûte d’amandes|Amandes, jus, zeste, sel.',
    'dresser|saumon, amandes|5||Recouvrir le saumon|Filets sur plaque, amandes dessus.',
    'enfourner|saumon|18|P|Cuire au four|15-20 min à 180 °C.',
    'bouillir|quinoa|15||Cuire le quinoa|',
    'couper|asperges|4||Tailler les asperges|En morceaux.',
    'bouillir|asperges|6|P|Asperges vapeur|',
    'dresser|saumon + quinoa + asperges|2|A|Dresser|'] },

{ nom: 'Sauté de légumes au tofu, riz', code: 'SG', fichier: 'Sauté de légumes SG',
  desc: 'Tofu doré, carottes, brocoli et poivrons sautés au gingembre, ail et sauce soja, riz.',
  ing: ['carotte|480|4', 'brocoli|400|1', 'poivron|300|2', 'tofu|400|400 g ferme', 'sauce soja|60|4 c. à s.', 'huile olive|42|3 c. à s.',
    'ail|10|2 gousses', 'gingembre|8|1 c. à s. râpé', 'riz|1560|600 g (cru) → cuit'],
  etapes: ['couper|carottes, brocoli, poivrons, tofu, ail, gingembre|14||Tailler|Rondelles, bouquets, lanières, tofu en dés, ail émincé, gingembre râpé.',
    'saisir|tofu|8||Dorer le tofu|2 c. à s. d’huile, toutes faces. Réserver.',
    'saisir|carottes, brocoli, poivrons|6||Sauter les légumes|Reste d’huile, ail, gingembre, légumes, 5-7 min.',
    'melanger|tofu, sauce soja|2||Remettre le tofu|Sauce soja, mélanger.',
    'bouillir|riz|18||Cuire le riz|',
    'dresser|sauté + riz|2|A|Dresser|Lit de riz.'] },

{ nom: 'Sauté de légumes et tofu, riz basmati', code: 'SG', fichier: 'Sauté de légumes au tofu SG',
  desc: 'Tofu ferme doré au wok, légumes sautés au gingembre, sauce soja, riz basmati.',
  ing: ['tofu|600|600 g ferme', 'brocoli|130|', 'carotte|130|', 'poivron|130|3 tasses de légumes au total', 'sauce soja|60|4 c. à s.',
    'huile olive|42|3 c. à s.', 'ail|10|2 gousses', 'gingembre|6|2 c. à c. râpé', 'riz basmati|1300|~500 g (cru) → cuit'],
  etapes: ['couper|tofu, légumes, ail, gingembre|12||Tailler|Tofu en dés, légumes en morceaux, ail émincé, gingembre râpé.',
    'saisir|tofu|8||Dorer le tofu|Wok, 2 c. à s. d’huile, chaque face. Réserver.',
    'saisir|légumes|6||Sauter les légumes|Reste d’huile, ail, gingembre, 5-7 min.',
    'mijoter|tofu, sauce soja|3||Finir|Tofu, sauce soja, 2-3 min.',
    'bouillir|riz basmati|15||Cuire le riz|',
    'dresser|sauté + riz|2|A|Dresser|'] },

{ nom: 'Soupe de lentilles corail, épinards et carottes', code: 'SG', fichier: 'Soupe de lentilles rouges SG',
  desc: 'Lentilles corail mijotées au bouillon et cumin, épinards, filet de citron.',
  ing: ['lentilles corail|780|1,5 tasse (cru) → cuit', 'oignon|150|1', 'carotte|240|2', 'bouillon de legumes|960|4 tasses', 'epinards|90|3 tasses',
    'huile olive|28|2 c. à s.', 'cumin|2|1 c. à c.', 'citron|40|q.s.', 'sel|0|q.s.'],
  etapes: ['couper|oignon, carottes|6||Tailler|Oignon haché, carottes en dés.',
    'saisir|oignon, carottes|6||Revenir|Casserole, huile.',
    'rincer|lentilles corail|2||Rincer les lentilles|',
    'mijoter|lentilles, bouillon, cumin|20|P|Mijoter 20 min|Porter à ébullition, réduire.',
    'mijoter|épinards|5||Épinards|5 min de plus.',
    'mixer|soupe|4||Mixer (optionnel)|Mixeur plongeant.',
    'dresser|soupe de lentilles|2|A|Dresser|Filet de citron.'] },

{ nom: 'Soupe de légumes', code: 'VG', fichier: 'Soupe de légumes VG',
  desc: 'Carottes, céleri, pommes de terre, courgette, haricots et tomates au bouillon, herbes de Provence.',
  ing: ['oignon|150|1', 'carotte|240|2', 'celeri|100|2 branches', 'pomme de terre|540|3', 'courgette|200|1', 'haricots blancs|250|1 boîte égouttée',
    'tomates concassees|400|1 boîte', 'bouillon de legumes|1440|6 tasses', 'huile olive|28|2 c. à s.', 'herbes de provence|2|1 c. à c.', 'persil|5|q.s.', 'sel|0|q.s.'],
  etapes: ['couper|oignon, carottes, céleri, pommes de terre, courgette|15||Tailler|Tout en dés.',
    'saisir|oignon, carottes, céleri|5||Revenir|Casserole, huile, 5 min.',
    'melanger|pommes de terre, courgette, haricots, tomates, bouillon|3||Mouiller|Herbes, sel, poivre.',
    'mijoter|soupe|23|P|Mijoter 20-25 min|Porter à ébullition, réduire.',
    'mixer|soupe|4||Mixer partiellement (optionnel)|',
    'dresser|soupe de légumes|2|A|Dresser|Persil.'] },

{ nom: 'Thon grillé, salsa de mangue, riz sauvage', code: 'PS', fichier: 'Steak de thon salsa mango PS (1)',
  desc: 'Steak de thon grillé, salsa fraîche mangue-oignon rouge-coriandre, riz sauvage.',
  ing: ['thon|900|6 steaks', 'mangue|500|2', 'oignon rouge|150|1', 'piment|10|1 jalapeño', 'coriandre|20|1/2 tasse',
    'jus de citron|60|4 c. à s.', 'riz sauvage|1200|~460 g (cru) → cuit', 'sel|0|q.s.'],
  etapes: ['couper|mangues, oignon rouge, piment, coriandre|10||Tailler la salsa|Mangue en dés, oignon et piment hachés, coriandre ciselée.',
    'melanger|salsa de mangue|3||Salsa|Citron, sel.',
    'bouillir|riz sauvage|40||Cuire le riz sauvage|',
    'assaisonner|thon|2||Saler le thon|',
    'saisir|thon|6||Griller le thon|Poêle moyenne, 2-3 min par face.',
    'dresser|thon + salsa + riz|2|A|Dresser|'] },

{ nom: 'Taboulé de lentilles et tofu aux herbes', code: 'VG', fichier: 'Taboulé de lentilles et tofu aux herbes',
  desc: 'Lentilles, boulgour, tofu doré, concombre, tomates, menthe et persil, citron.',
  ing: ['lentilles|200|1 tasse cuites', 'tofu|300|300 g', 'boulgour|280|1 tasse cuit', 'concombre|300|1', 'tomate|240|2', 'oignon rouge|75|1/2',
    'menthe|10|1/4 tasse', 'persil|10|1/4 tasse', 'huile olive|56|4 c. à s.', 'jus de citron|80|2 citrons', 'sel|0|q.s.'],
  etapes: ['couper|tofu, concombre, tomates, oignon rouge, menthe, persil|12||Tailler|Tofu, concombre et tomates en dés, oignon haché, herbes ciselées.',
    'saisir|tofu|8||Dorer le tofu|2 c. à s. d’huile, feu moyen, croustillant. Réserver.',
    'melanger|lentilles, boulgour, légumes, herbes|4||Assembler|',
    'fouetter|huile, citron|2||Vinaigrette|Reste d’huile, citron, sel, poivre.',
    'dresser|taboulé + tofu|2|A|Dresser|Tofu dessus, vinaigrette.'] },

{ nom: 'Tacos de poisson', code: 'PP', fichier: 'Tacos de poisson PP',
  desc: 'Poisson blanc poêlé, tortilla de maïs, chou émincé, avocat, sauce yaourt-citron, coriandre.',
  ing: ['merlu|900|6 filets de poisson blanc', 'tortilla mais|360|6', 'chou|500|1/2', 'avocat|340|2', 'yaourt nature|120|1/2 tasse',
    'jus de citron|30|2 c. à s.', 'coriandre|10|q.s.', 'huile olive|14|un peu', 'sel|0|q.s.'],
  etapes: ['couper|chou, avocats, coriandre|10||Tailler|Chou émincé, avocat en dés, coriandre hachée.',
    'saisir|poisson|10||Cuire le poisson|Poêle, un peu d’huile, sel, poivre, 4-5 min par face.',
    'fouetter|yaourt, citron|3||Sauce yaourt|Sel, poivre.',
    'saisir|tortillas|4|A|Chauffer les tortillas|',
    'dresser|tacos|3|A|Monter les tacos|Poisson, chou, avocat, sauce, coriandre.'] },

{ nom: 'Truite aux herbes', code: 'PM', fichier: 'Truite aux herbes fine PM',
  desc: 'Filet de truite au four, citron, ciboulette et persil, légumes vapeur.',
  ing: ['truite|900|6 filets', 'huile olive|84|6 c. à s.', 'citron|100|1', 'ciboulette|10|1/4 tasse', 'persil|10|1/4 tasse', 'legumes|600|vapeur, pour accompagner', 'sel|0|q.s.'],
  etapes: ['enfourner|four|10|P|Préchauffer|200 °C.',
    'couper|citron, ciboulette, persil|5||Tailler|Citron en rondelles, herbes hachées.',
    'huiler|truite|4||Préparer la plaque|Filets sur plaque, huile, sel, poivre, citron, herbes.',
    'enfourner|truite|18|P|Cuire au four|15-20 min à 200 °C.',
    'bouillir|légumes|8|P|Légumes vapeur|',
    'dresser|truite + légumes|2|A|Dresser|'] },

{ nom: 'Truite vapeur, écrasé de patate douce', code: 'PM', fichier: 'Truite vapeur et son écrasé de patate douce PM',
  desc: 'Filet de truite vapeur, écrasé de patate douce à l’huile d’olive et ciboulette, légumes vapeur.',
  ing: ['truite|900|6 filets', 'patate douce|600|600 g', 'huile olive|42|3 c. à s.', 'ail|10|2 gousses', 'ciboulette|10|1/4 tasse', 'legumes|600|vapeur, pour accompagner', 'sel|0|q.s.'],
  etapes: ['couper|patates douces, ail, ciboulette|8||Tailler|Patates douces pelées en cubes, ail émincé, ciboulette ciselée.',
    'bouillir|patates douces|18|P|Cuire les patates douces|Eau bouillante, 15-20 min.',
    'mixer|patates douces|5||Écraser|1 c. à s. d’huile, sel, poivre.',
    'bouillir|truite|9|P|Truite vapeur|8-10 min.',
    'bouillir|légumes|8|P|Légumes vapeur|',
    'dresser|truite + écrasé + légumes|2|A|Dresser|'] }
];
